### ISSUE TITLE
Location doesn't work on emulator

### ISSUE THREAD

**Issue by niamotullah** [Lyokone/flutterlocation#1010]
**Describe the bug**
A clear and concise description of what the bug is. Have you tried running `flutter clean` first ?

**Expected behavior**

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
 - iOS, Version XX [e.g. 10], simulator or real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**
```

W/GoogleApiManager( 2710): The service for com.google.android.gms.internal.location.zzdz is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
E/flutter ( 2710): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(UNEXPECTED_ERROR, 17: API: LocationServices.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}, null, null)
E/flutter ( 2710): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter ( 2710): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #3      MethodChannelLocation.getLocation (package:location_platform_interface/src/method_channel_location.dart:83:9)
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): #4      _LocationInputState._getCurrentLocation (package:favorite_places/widget/location_input.dart:43:21)
E/flutter ( 2710): <asynchronous suspension>
E/flutter ( 2710): 
D/EGL_emulation( 2710): app_time_stats: avg=14.13ms min=3.68ms max=67.21ms count=57
D/EGL_emulation( 2710): app_time_stats: avg=9.98ms min=5.84ms max=19.73ms count=60
D/EGL_emulation( 2710): app_time_stats: avg=8.72ms min=4.41ms max=16.00ms count=61
D/EGL_emulation( 2710): app_time_stats: avg=11.08ms min=2.76ms max=19.93ms count=61
D/EGL_emulation( 2710): app_time_stats: avg=10.50ms min=2.69ms max=17.87ms count=61
W/GooglePlayServicesUtil( 2710): com.example.favorite_places requires the Google Play Store, but it is missing.
W/GoogleApiManager( 2710): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
W/GooglePlayServicesUtil( 2710): com.example.favorite_places requires the Google Play Store, but it is missing.
W/GoogleApiManager( 2710): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
```

``` shell
some logs
```

**Comment by wbernadoque** [comment]
I'm having the same error here, it only works on physical devices. When I'm using emulator, the getLocation just doesn't return the lat long.

**Comment by Lyokone** [comment]
Already fixed. The log is unambiguous: `SERVICE_INVALID`/"requires the Google Play Store, but it is missing" — an emulator image without Google Play Services. `location: ^7.0.1` predates the non-GMS fallback added in a prior session's work. Current `startRequestingLocation()` explicitly checks for this exact scenario (`isApiUnavailable()`, matching `ConnectionResult.SERVICE_INVALID` among other codes) and falls back to the framework `LocationManager` instead of throwing. If this still reproduces on the current release, please reopen with a fresh log.
