### ISSUE TITLE
Execution failed for task ':app:packageDebug'. > !zip.isFile()

### ISSUE THREAD

**Issue by bens-pixeltechnologies** [Lyokone/flutterlocation#14]
I am using the windows emulator and I get the above exception when I add the location: "^1.1.6" to my pubspec.yaml
file details:
name: testflutter
description: A new flutter project.

dependencies:
  dartson: "^0.2.7"
  cipher: "^0.7.1"
  location: "^1.1.6"  
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true

Below is my verbose flutter run. I have commented out all code relating to location it seems just the dependency is causing issues. Any ideas?

c:\testflutter>flutter run -v
[  +26 ms] [c:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/alpha
[   +1 ms] [c:\flutter\] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +2 ms] [c:\flutter\] git log -n 1 --pretty=format:%H
[  +23 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 973304d5fbf737510ecc250b93d9ee2e872b563f
[   +2 ms] [c:\flutter\] git log -n 1 --pretty=format:%ar
[  +15 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 5 months ago
[+5335 ms] Failed to check Flutter version in the remote repository: VersionCheckError: Command exited with code 128: git log __flutter_version_check__/alpha -n 1 --pretty=format:%ad --date=iso
           Standard error: fatal: ambiguous argument '__flutter_version_check__/alpha': unknown revision or path not in the working tree.
           Use '--' to separate paths from revisions, like this:
           'git <command> [<revision>...] -- [<file>...]'

[ +259 ms] Listing devices using C:\Android\android-sdk\platform-tools\adb
[   +1 ms] C:\Android\android-sdk\platform-tools\adb devices -l
[  +43 ms] Exit code 0 from: C:\Android\android-sdk\platform-tools\adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
[  +19 ms] C:\Android\android-sdk\platform-tools\adb -s emulator-5554 shell getprop
[ +564 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[ +209 ms] Using gradle from C:\Program Files\Android\Android Studio1\gradle\gradle-3.2\bin\gradle.bat.
[   +3 ms] [android\] C:\Program Files\Android\Android Studio1\gradle\gradle-3.2\bin\gradle.bat app:properties
[+1672 ms] Exit code 0 from: C:\Program Files\Android\Android Studio1\gradle\gradle-3.2\bin\gradle.bat app:properties
[   +3 ms] C:\Android\android-sdk\build-tools\26.0.2\aapt dump badging C:\RND\testflutter\build\app/outputs/apk/app.apk
[  +12 ms] Exit code 0 from: C:\Android\android-sdk\build-tools\26.0.2\aapt dump badging C:\RND\testflutter\build\app/outputs/apk/app.apk
[        ] package: name='com.yourcompany.testflutter' versionCode='1' versionName='0.0.1' platformBuildVersionName='7.1.1'
           sdkVersion:'16'
           targetSdkVersion:'21'
           uses-permission: name='android.permission.INTERNET'
           uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
           application-label:'testflutter'
           application-icon-160:'res/mipmap-mdpi-v4/ic_launcher.png'
           application-icon-240:'res/mipmap-hdpi-v4/ic_launcher.png'
           application-icon-320:'res/mipmap-xhdpi-v4/ic_launcher.png'
           application-icon-480:'res/mipmap-xxhdpi-v4/ic_launcher.png'
           application-icon-640:'res/mipmap-xxxhdpi-v4/ic_launcher.png'
           application: label='testflutter' icon='res/mipmap-mdpi-v4/ic_launcher.png'
           application-debuggable
           launchable-activity: name='com.yourcompany.testflutter.MainActivity'  label='' icon=''
           feature-group: label=''
             uses-feature: name='android.hardware.faketouch'
             uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
             uses-feature: name='android.hardware.location'
             uses-implied-feature: name='android.hardware.location' reason='requested android.permission.ACCESS_FINE_LOCATION permission'
           main
           supports-screens: 'small' 'normal' 'large' 'xlarge'
           supports-any-density: 'true'
           locales: '--_--'
           densities: '160' '240' '320' '480' '640'
           native-code: 'armeabi-v7a' 'x86' 'x86_64'
[  +22 ms] C:\Android\android-sdk\platform-tools\adb -s emulator-5554 logcat -v time -t 1
[  +51 ms] Exit code 0 from: C:\Android\android-sdk\platform-tools\adb -s emulator-5554 logcat -v time -t 1
[        ] --------- beginning of main
           10-25 06:03:25.336 I/DeviceStateChecker( 2519): DeviceStateChecker cancelled
[   +5 ms] C:\Android\android-sdk\platform-tools\adb -s emulator-5554 logcat -v time
[ +251 ms] DependencyChecker: c:\RND\testflutter\.packages is newer than 2017-10-25 17:02:11.000
[   +6 ms] C:\Android\android-sdk\platform-tools\adb version
[  +19 ms] Android Debug Bridge version 1.0.39
           Revision 3db08f2c6889-android
           Installed as C:\Android\android-sdk\platform-tools\adb.EXE
[   +6 ms] C:\Android\android-sdk\platform-tools\adb start-server
[ +166 ms] Building APK
[  +71 ms] Found plugin location at C:\Users\bensuryn\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\location-1.1.6\
[  +37 ms] Using gradle from C:\Program Files\Android\Android Studio1\gradle\gradle-3.2\bin\gradle.bat.
[   +3 ms] Running 'gradle assembleDebug'...
[   +3 ms] [android\] C:\Program Files\Android\Android Studio1\gradle\gradle-3.2\bin\gradle.bat -Ptarget=c:\RND\testflutter\lib/main.dart assembleDebug
[+1560 ms] Incremental java compilation is an incubating feature.
[   +7 ms] The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
[   +2 ms]      at build_9dkbe9x2d3p3h3i98e013hzot$_run_closure2.doCall(C:\RND\testflutter\android\build.gradle:20)
[  +74 ms] WARNING: Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (25.2.0) and test app (25.0.0) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
[  +44 ms] :app:flutterBuildX86Jar UP-TO-DATE
[   +1 ms] :app:preBuild UP-TO-DATE
[   +2 ms] :app:preDebugBuild UP-TO-DATE
[   +2 ms] :app:checkDebugManifest
[   +2 ms] :app:preProfileBuild UP-TO-DATE
[   +2 ms] :app:preReleaseBuild UP-TO-DATE
[   +1 ms] :location:preBuild UP-TO-DATE
[   +1 ms] :location:preReleaseBuild UP-TO-DATE
[   +2 ms] :location:checkReleaseManifest
[   +2 ms] :location:preDebugAndroidTestBuild UP-TO-DATE
[   +1 ms] :location:preDebugBuild UP-TO-DATE
[   +1 ms] :location:preDebugUnitTestBuild UP-TO-DATE
[   +1 ms] :location:preReleaseUnitTestBuild UP-TO-DATE
[   +1 ms] :location:prepareComAndroidSupportSupportCompat2520Library UP-TO-DATE
[   +1 ms] :location:prepareComAndroidSupportSupportCoreUi2520Library UP-TO-DATE
[   +1 ms] :location:prepareComAndroidSupportSupportCoreUtils2520Library UP-TO-DATE
[   +1 ms] :location:prepareComAndroidSupportSupportFragment2520Library UP-TO-DATE
[   +1 ms] :location:prepareComAndroidSupportSupportMediaCompat2520Library UP-TO-DATE
[   +1 ms] :location:prepareComAndroidSupportSupportV42520Library UP-TO-DATE
[   +3 ms] :location:prepareComGoogleAndroidGmsPlayServicesBase1142Library UP-TO-DATE
[   +2 ms] :location:prepareComGoogleAndroidGmsPlayServicesBaseLicense1142Library UP-TO-DATE
[  +13 ms] :location:prepareComGoogleAndroidGmsPlayServicesBasement1142Library UP-TO-DATE
[   +2 ms] :location:prepareComGoogleAndroidGmsPlayServicesBasementLicense1142Library UP-TO-DATE
[   +1 ms] :location:prepareComGoogleAndroidGmsPlayServicesLocation1142Library UP-TO-DATE
[   +2 ms] :location:prepareComGoogleAndroidGmsPlayServicesLocationLicense1142Library UP-TO-DATE
[   +2 ms] :location:prepareComGoogleAndroidGmsPlayServicesTasks1142Library UP-TO-DATE
[   +3 ms] :location:prepareComGoogleAndroidGmsPlayServicesTasksLicense1142Library UP-TO-DATE
[   +1 ms] :location:prepareReleaseDependencies
[   +8 ms] :location:compileReleaseAidl UP-TO-DATE
[   +2 ms] :location:compileReleaseNdk UP-TO-DATE
[   +1 ms] :location:compileLint UP-TO-DATE
[   +2 ms] :location:copyReleaseLint UP-TO-DATE
[   +6 ms] :location:compileReleaseRenderscript UP-TO-DATE
[   +3 ms] :location:generateReleaseBuildConfig UP-TO-DATE
[   +2 ms] :location:generateReleaseResValues UP-TO-DATE
[   +1 ms] :location:generateReleaseResources UP-TO-DATE
[  +47 ms] :location:mergeReleaseResources UP-TO-DATE
[   +3 ms] :location:processReleaseManifest UP-TO-DATE
[  +20 ms] :location:processReleaseResources UP-TO-DATE
[   +1 ms] :location:generateReleaseSources UP-TO-DATE
[   +3 ms] :location:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
[  +14 ms] :location:compileReleaseJavaWithJavac UP-TO-DATE
[   +6 ms] :location:extractReleaseAnnotations UP-TO-DATE
[   +2 ms] :location:mergeReleaseShaders UP-TO-DATE
[   +2 ms] :location:compileReleaseShaders UP-TO-DATE
[   +1 ms] :location:generateReleaseAssets UP-TO-DATE
[   +2 ms] :location:mergeReleaseAssets UP-TO-DATE
[   +2 ms] :location:mergeReleaseProguardFiles UP-TO-DATE
[   +1 ms] :location:packageReleaseRenderscript UP-TO-DATE
[   +2 ms] :location:packageReleaseResources UP-TO-DATE
[   +1 ms] :location:processReleaseJavaRes UP-TO-DATE
[   +2 ms] :location:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
[   +3 ms] :location:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[   +2 ms] :location:mergeReleaseJniLibFolders UP-TO-DATE
[   +2 ms] :location:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
[   +1 ms] :location:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
[   +3 ms] :location:bundleRelease UP-TO-DATE
[   +2 ms] :app:prepareComAndroidSupportSupportCompat2520Library UP-TO-DATE
[   +2 ms] :app:prepareComAndroidSupportSupportCoreUi2520Library UP-TO-DATE
[   +2 ms] :app:prepareComAndroidSupportSupportCoreUtils2520Library UP-TO-DATE
[   +2 ms] :app:prepareComAndroidSupportSupportFragment2520Library UP-TO-DATE
[   +3 ms] :app:prepareComAndroidSupportSupportMediaCompat2520Library UP-TO-DATE
[   +2 ms] :app:prepareComAndroidSupportSupportV42520Library UP-TO-DATE
[  +11 ms] :app:prepareComGoogleAndroidGmsPlayServicesBase1104Library UP-TO-DATE
[  +10 ms] :app:prepareComGoogleAndroidGmsPlayServicesBasement1104Library UP-TO-DATE
[   +2 ms] :app:prepareComGoogleAndroidGmsPlayServicesLocation1104Library UP-TO-DATE
[   +2 ms] :app:prepareComGoogleAndroidGmsPlayServicesTasks1104Library UP-TO-DATE
[   +2 ms] :app:prepareComLyokoneLocationLocation10SNAPSHOTLibrary UP-TO-DATE
[   +1 ms] :app:prepareDebugDependencies
[   +6 ms] :app:compileDebugAidl UP-TO-DATE
[   +3 ms] :app:compileDebugRenderscript UP-TO-DATE
[   +1 ms] :app:generateDebugBuildConfig UP-TO-DATE
[   +1 ms] :app:flutterDependenciesDebug UP-TO-DATE
[ +199 ms] :app:flutterBuildDebug UP-TO-DATE
[   +3 ms] :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] :app:compileDebugShaders UP-TO-DATE
[   +1 ms] :app:generateDebugAssets UP-TO-DATE
[   +5 ms] :app:mergeDebugAssets UP-TO-DATE
[   +1 ms] :app:copyFlutterAssetsDebug UP-TO-DATE
[   +1 ms] :app:generateDebugResValues UP-TO-DATE
[   +1 ms] :app:generateDebugResources UP-TO-DATE
[  +34 ms] :app:mergeDebugResources UP-TO-DATE
[   +6 ms] :app:processDebugManifest UP-TO-DATE
[  +11 ms] :app:processDebugResources UP-TO-DATE
[   +1 ms] :app:generateDebugSources UP-TO-DATE
[   +4 ms] :app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
[  +11 ms] :app:compileDebugJavaWithJavac UP-TO-DATE
[   +1 ms] :app:compileDebugNdk UP-TO-DATE
[   +1 ms] :app:compileDebugSources UP-TO-DATE
[   +5 ms] :app:transformClassesWithDexForDebug UP-TO-DATE
[   +2 ms] :app:mergeDebugJniLibFolders UP-TO-DATE
[   +4 ms] :app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
[   +1 ms] :app:processDebugJavaRes UP-TO-DATE
[   +3 ms] :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[   +1 ms] :app:validateSigningDebug
[  +17 ms] :app:packageDebug FAILED
[   +3 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:packageDebug'.
[   +2 ms] > !zip.isFile()
[   +2 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[   +2 ms] BUILD FAILED
[   +1 ms] Total time: 2.229 secs
[ +370 ms] "flutter run" took 6,094ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:244)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:192)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:83)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:334)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:223)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:183)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:321)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:210)
<asynchronous suspension>
#9      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:210)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:156)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#14     Future.Future.sync (dart:async/future.dart:208)
#15     CommandRunner.run (package:args/command_runner.dart:109)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:156)
#17     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#18     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#19     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#20     _rootRun (dart:async/zone.dart:1120)
#21     _CustomZone.run (dart:async/zone.dart:1001)
#22     runZoned (dart:async/zone.dart:1465)
#23     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#24     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#25     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#26     main (file:///c:/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

[ +299 ms] ensureAnalyticsSent: 252ms
[   +4 ms] exiting with code 1

**Comment by bens-pixeltechnologies** [comment]
Was using and older version of flutter/dart: 
Doesnt work with:
flutter --version
Flutter - channel alpha - https://github.com/flutter/flutter.git
Framework - revision 973304d5fb (5 months ago) - 2017-05-18 17:31:57 -0700
Engine - revision f99d3ef108
Tools - Dart 1.23.0-dev.11.11

Does work with:
flutter --version
Flutter -channel alpha -https://github.com/flutter/flutter.git
Framework -revision e8aa40eddd (9 days ago) -2017-10-17 15:42:40 -0700
Engine -revision 7c4142808c
Tools -Dart 1.25.0-dev.11.0
