### ISSUE TITLE
getLocation() just return null

### ISSUE THREAD

**Issue by danielbandeir** [Lyokone/flutterlocation#160]
Hi, I'm trying to pick a location, but every time catch null, I configured all like the getting start, but every time that I call getLocation(), return null.

```dart
class _dashboardState extends State<dashboard> {
  LocationData currentLocation;
  var location = new Location();
  String error;

  @override
  void initState(){
    super.initState();
    this._getCurrentLocation();
  }

  // pegar a localização atual (resolver futuramente)
  Future<LocationData> _getCurrentLocation() async {
    var _permission = location.hasPermission();

    try {
      if (_permission == true){
        currentLocation = await location.getLocation();
        return currentLocation;
      }
      else{
        location.requestPermission();
        if (_permission == true){
          currentLocation = await location.getLocation();
        }
      }
    } on PlatformException catch (e) {
      if (e.code == 'PERMISSION_DENIED') {
        error = 'Permission denied';
      }
      currentLocation = null;
    }
    return currentLocation;
  }

```

Log

```
I/flutter ( 8753): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8753): The following NoSuchMethodError was thrown building dashboard(dirty, dependencies: [MediaQuery],
I/flutter ( 8753): state: _dashboardState#25ac0):
I/flutter ( 8753): The getter 'latitude' was called on null.
I/flutter ( 8753): Receiver: null
I/flutter ( 8753): Tried calling: latitude
I/flutter ( 8753): When the exception was thrown, this was the stack:
I/flutter ( 8753): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 8753): #1      _dashboardState.build (package:testefl/dashboard.dart:125:46)
I/flutter ( 8753): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter ( 8753): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
I/flutter ( 8753): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter ( 8753): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter ( 8753): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)

```

**Comment by danielbandeir** [comment]
> ```dart
> Location
> ```
