### ISSUE TITLE
Android: Crashed when checking for Location permission

### ISSUE THREAD

**Issue by sunilmishra** [Lyokone/flutterlocation#174]
E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/ActivityCompat;
        at com.lyokone.location.LocationPlugin.checkPermissions(LocationPlugin.java:340)
        at com.lyokone.location.LocationPlugin.onMethodCall(LocationPlugin.java:155)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:327)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.ActivityCompat" on path: DexPathList[[zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/base.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_resources_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/base.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.searchtoilet.toiletfinder.beta-zWQeOxeWfBo2i1PzugFpAw==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /system/product/lib]]
    	at dalv
A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).

**Comment by sunilmishra** [comment]
android.useAndroidX=true 
fixed the issue.
