### ISSUE TITLE
App doesn't request permission and crash

### ISSUE THREAD

**Issue by TurkiWalid** [Lyokone/flutterlocation#188]
**Describe the bug**
App cound not launch

**Tested on:**
 - Android, API Level 23, real device
- Location v ^2.3.5

**Other plugins:**
 - Firebase cloud messaging

**Additional logs**

``` 

Built build\app\outputs\apk\debug\app-debug.apk.

E/flutter (17993): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/app/ActivityCompat;

E/flutter (17993): 	at com.lyokone.location.LocationPlugin.checkPermissions(LocationPlugin.java:357)

E/flutter (17993): 	at com.lyokone.location.LocationPlugin.onMethodCall(LocationPlugin.java:153)

E/flutter (17993): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)

E/flutter (17993): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)

E/flutter (17993): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)

E/flutter (17993): 	at android.os.MessageQueue.nativePollOnce(Native Method)

E/flutter (17993): 	at android.os.MessageQueue.next(MessageQueue.java:323)

E/flutter (17993): 	at android.os.Looper.loop(Looper.java:143)

E/flutter (17993): 	at android.app.ActivityThread.main(ActivityThread.java:7225)

E/flutter (17993): 	at java.lang.reflect.Method.invoke(Native Method)

E/flutter (17993): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

E/flutter (17993): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

E/flutter (17993): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.ActivityCompat" on path: DexPathList[[zip file "/data/app/com.*******.test_push-1/base.apk"],nativeLibraryDirectories=[/data/app/com.******.test_push-1/lib/arm, /data/app/com.*****.test_push-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

E/flutter (17993): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

E/flutter (17993): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

E/flutter (17993): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

E/flutter (17993): 	... 12 more

E/flutter (17993): 	Suppressed: java.lang.ClassNotFoundException: androidx.core.app.ActivityCompat

E/flutter (17993): 		at java.lang.Class.classForName(Native Method)

E/flutter (17993): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

E/flutter (17993): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

E/flutter (17993): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

E/flutter (17993): 		... 13 more

E/flutter (17993): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

E/flutter (17993):

F/flutter (17993): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).

F/libc    (17993): Fatal signal 6 (SIGABRT), code -6 in tid 17993 (anger.test_push)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Build fingerprint: 'samsung/trltetmofrp/trltetmo:6.0.1/______'

Revision: '12'

ABI: 'arm'

pid: 17993, tid: 17993, name: anger.test_push  >>> com.*****.test_push <<<

signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------

Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).

'

    r0 00000000  r1 00004649  r2 00000006  r3 b6f95b94

    r4 b6f95b9c  r5 b6f95b4c  r6 0000000b  r7 0000010c

    r8 bea04c94  r9 bea04ce0  sl 00000066  fp ad951890

    ip 00000006  sp bea04b70  lr b6cf5c11  pc b6cf8000  cpsr 400f0010

backtrace:

    #00 pc 00042000  /system/lib/libc.so (tgkill+12)

    #01 pc 0003fc0d  /system/lib/libc.so (pthread_kill+32)

    #02 pc 0001c397  /system/lib/libc.so (raise+10)

    #03 pc 00019615  /system/lib/libc.so (__libc_android_abort+34)

    #04 pc 00017568  /system/lib/libc.so (abort+4)

    #05 pc 00af85ab  /data/app/com.*****.test_push-1/lib/arm/libflutter.so (offset 0xaea000)

    #06 pc 00aef115  /data/app/com.*****.test_push-1/lib/arm/libflutter.so (offset 0xaea000)

    #07 pc 00aede03  /data/app/com.*****.test_push-1/lib/arm/libflutter.so (offset 0xaea000)

    #08 pc 00b1dc13  /data/app/com.*****.test_push-1/lib/arm/libflutter.so (offset 0xaea000)

    #09 pc 00af8cf3  /data/app/com.*****.test_push-1/lib/arm/libflutter.so (offset 0xaea000)

    #10 pc 00afb7ff  /data/app/com.*****.test_push-1/lib/arm/libflutter.so (offset 0xaea000)

    #11 pc 00012e93  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+530)

    #12 pc 00012f63  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+130)

    #13 pc 000873cd  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)

    #14 pc 02f83575  /system/framework/arm/boot.oat (offset 0x2f83000)

Tombstone written to: /data/tombstones/tombstone_04

Lost connection to device.

Exited (sigterm)


```

**Comment by kamami** [comment]
Same error with me... Please fix this soon. 
Flutter v1.6.6
