### ISSUE TITLE
Failed to open event stream: 

### ISSUE THREAD

**Issue by devhci** [Lyokone/flutterlocation#234]
**Describe the bug**
 Failed to open event stream:
 PlatformException was thrown while activating platform stream on channel
I/flutter (24526): lyokone/locationstream:

Version 
location 2.3.5

**Expected behavior**
should send location  onLocationChanged . 

**Tested on:**
 - Android, API Level 28
 - Android, Version 9 [e.g. 10],  real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**How I used the plugin **
```
location.Location locationService = location.Location();
   class LocationProbe extends StreamProbe {
  void onInitialize(Measure measure) async {
    super.onInitialize(measure);
    await _getPermission();
  }
  Stream<LocationDatum> get stream => locationService
      .onLocationChanged()
      .asBroadcastStream()
      .map((location) => LocationDatum.fromLocationData(location));

  Future<bool> _getPermission() async {
    bool permission = false;
    bool enabled = await locationService.serviceEnabled();
    if (enabled) {
      permission = await locationService.hasPermission();
      if (!permission) permission = await locationService.requestPermission();
    }
    return permission;
  }
} 
```

Error traces 
``` shell
E/EventChannel#lyokone/locationstream: Failed to open event stream
    java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
        at com.lyokone.location.LocationPlugin.onListen(LocationPlugin.java:466)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)


2019-10-01 18:13:15.541 22072-22183/com.cachet.reafelapp I/flutter: Location service available: true
2019-10-01 18:13:15.551 22072-22072/com.cachet.reafelapp W/Activity: Can request only one set of permissions at a time
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: The following PlatformException was thrown while activating platform stream on channel
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: lyokone/locationstream:
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: PlatformException(error, Attempt to invoke interface method 'void
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String,
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: java.lang.Object)' on a null object reference, null)
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: When the exception was thrown, this was the stack:
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: <asynchronous suspension>
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:504:29)
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: <asynchronous suspension>
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: #14     StreamProbe.onStart (package:carp_mobile_sensing/runtime/probes.dart:425:27)
2019-10-01 18:13:15.625 22072-22183/com.cachet.reafelapp I/flutter: #15     _InitializedState.start (package:carp_mobile_sensing/runtime/probes.dart:237:11)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #16     AbstractProbe.start (package:carp_mobile_sensing/runtime/probes.dart:151:33)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #17     TaskExecutor.onStart (package:carp_mobile_sensing/runtime/executors.dart:113:15)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #19     TaskExecutor.onStart (package:carp_mobile_sensing/runtime/executors.dart:101:17)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #20     _InitializedState.start (package:carp_mobile_sensing/runtime/probes.dart:237:11)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #21     AbstractProbe.start (package:carp_mobile_sensing/runtime/probes.dart:151:33)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #22     StudyExecutor.onStart (package:carp_mobile_sensing/runtime/executors.dart:78:16)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #24     StudyExecutor.onStart (package:carp_mobile_sensing/runtime/executors.dart:71:17)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #25     _InitializedState.start (package:carp_mobile_sensing/runtime/probes.dart:237:11)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #26     AbstractProbe.start (package:carp_mobile_sensing/runtime/probes.dart:151:33)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #27     StudyController.start (package:carp_mobile_sensing/runtime/study_controller.dart:115:14)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #29     StudyController.start (package:carp_mobile_sensing/runtime/study_controller.dart:112:21)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #30     Sensing.start (package:reafel_app/sensing/sensing.dart:50:16)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #41     StudyController.initialize (package:carp_mobile_sensing/runtime/study_controller.dart)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #52     Device.getDeviceInfo (package:carp_mobile_sensing/domain/device_info.dart)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #63     DeviceInfoPlugin.androidInfo (package:device_info/device_info.dart)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #74     MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: #85     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: (elided 78 frames from package dart:async and package dart:async-patch)
2019-10-01 18:13:15.626 22072-22183/com.cachet.reafelapp I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2019-10-01 18:13:15.656 22072-22183/com.cachet.reafelapp I/flutter: Location permission: true
```

**Comment by renanyoy** [comment]
I have same behavior, works on iOS, not on android (but still request location permission)

**Comment by marianoarga** [comment]
Don't stale
