### ISSUE TITLE
LocationPlugin.java is reported as crashing in Crashlytics (Android)

### ISSUE THREAD

**Issue by algirdasmac** [Lyokone/flutterlocation#236]
**Describe the bug**
Crashlytics dashboard is reporting, that approximately 7% of users are crashing because of this plugin.

**Expected behavior**
Not to crash app.

**Tested on:**
HUAWEI P20
Samsung Galaxy A9 (2018)
HUAWEI Mate 10 Pro
Samsung Galaxy A3 (2017)
Samsung Galaxy S9
HUAWEI P20 lite
Samsung Galaxy A8(2018)
Samsung Galaxy S7 edge
Samsung Galaxy S6
Samsung Galaxy S6 edge
HUAWEI P30 lite
Samsung Galaxy S7
Xiaomi Mi A1
CUBOT NOTE S
Sony Xperia Z5 Premium
Samsung Galaxy XCover4
and many more ...

**Additional logs**
One crash is reported as
`LocationPlugin.java line 243`
`com.lyokone.location.LocationPlugin.onActivityResult`
``` shell
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=0, data=Intent { (has extras) }} to activity {lt.lastmile.client/lt.lastmile.client.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4936)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4978)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at com.lyokone.location.LocationPlugin.onActivityResult(LocationPlugin.java:243)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
       at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
       at android.app.Activity.dispatchActivityResult(Activity.java:7775)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4929)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4978)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7470)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
Another as
`LocationPlugin.java line 241`
`com.lyokone.location.LocationPlugin.onActivityResult`
```shell
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=4097, result=-1, data=Intent { (has extras) }} to activity {lt.lastmile.client/lt.lastmile.client.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at com.lyokone.location.LocationPlugin.onActivityResult(LocationPlugin.java:241)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
       at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
       at android.app.Activity.dispatchActivityResult(Activity.java:7762)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

**Comment by igoriuz** [comment]
I've run into something similar. I guess it happens when the phone is in airplane mode/ without internet connectivity but gps is still on.

**Comment by prasant10050** [comment]
Hi,I am still facing this issue now on my production app 
Devices
Micromax(Canvas Xpress 4g,Micromax Bharat 2 Plus,
MI
Samsung (Galaxy On7 Pro,Galaxy J2 Pro,Galaxy J2,Canvas Juice 4G,Galaxy J5
OppO (A37f)
GIONEE(A1 Lite)
