### ISSUE TITLE
Get exceptions on iOS

### ISSUE THREAD

**Issue by Velek** [Lyokone/flutterlocation#274]
**Describe the bug**
Fails to retrieve location under iOS.  Worked previously before recent updates to XCode and Flutter.

**Expected behavior**
Receive location from iOS GPS

**Tested on:**
 - iOS, Version 13 [e.g. 10], simulator and real devices.

**Other plugins:**
Working on my own platform channels and streams, but I don't think they'd interfere.

**Additional logs**

``` shell
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           21.8s
Syncing files to device iPhone 11 Pro Max...
	path: satisfied (Path is satisfied), interface: en10
flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
═══════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: MissingPluginException(No implementation found for method listen on channel lyokone/locationstream)
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermission on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.requestPermission (package:location/location.dart:70:16)
#2      new LocationService (package:run_vmc/model/location_service.dart:20:14)
#3      initLocator (package:run_vmc/model/locator.dart:11:32)
#4      main (package:run_vmc/main.dart:18:3)
#5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1502:12)
#10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#12     _RawReceivePortI<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getLocation on channel lyokone/location)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Location.getLocation (package:location/location.dart:61:8)
#2      AWGovCache._updateLocation (package:run_vmc/model/aw.gov.dart:110:39)
#3      AWGovCache.getStationList (package:run_vmc/model/aw.gov.dart:116:5)
#4      AWGovCache.loadedStationsSorted (package:run_vmc/model/aw.gov.dart:223:45)
#5      StationListView.build.<anonymous closure>.<anonymous closure> (package:run_vmc/station_list_view.dart:52:29)
#6      new ListView.separated.<anonymous closure> (package:flutter/src/widgets/scroll_view.dart:1042:34)
#7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
#8      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1260:67)
#9      _H<…>
```

**Comment by Lyokone** [comment]
Hey ! It seems that the plugin is not correctly installed on iOS since Flutter does not find any handler for `lyokone/location`. Can you give a reproducible example so I can help you ?
