### ISSUE TITLE
MissingPluginException(No implementation found for method requestService on channel lyokone/location)

### ISSUE THREAD

**Issue by joshuakoh1** [Lyokone/flutterlocation#369]
**Describe the bug**
```
E/flutter (24030): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestService on channel lyokone/location)
E/flutter (24030): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (24030): <asynchronous suspension>
E/flutter (24030): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (24030): #2      MethodChannelLocation.requestService (package:location_platform_interface/src/method_channel_location.dart:127:45)
E/flutter (24030): #3      Location.requestService (package:location/location.dart:68:38)
E/flutter (24030): #4      setCurrentLocation 
E/flutter (24030): #5      getCurrentLocation 
```
**Expected behavior**
Location to work

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
Real Device, API 29
Plugin version ^3.0.0
Flutter v1.17.1

 - iOS, Version XX [e.g. 10], simulator or real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by IsaacGonzalez** [comment]
I'm having the same Issue. 

It's all working when running the app on my emulator or physical device trough my IDE. But when I build a release APK, and then install it. I get this error.

**Comment by EmadBeltaje** [comment]
any update here? 
@IsaacGonzalez @joshuakoh1
