### ISSUE TITLE
Error at application start 

### ISSUE THREAD

**Issue by Galahand** [Lyokone/flutterlocation#38]
I recently updated firebase plugins (cloud_firestore to 0.7.1 and firebase_auth to 0.5.10) but when i did that the app started to crash on the start with no messages in the Run tab but in the logcat i got this message:

    --------- beginning of crash
05-22 10:26:00.074 28690-28690/com.pitahaya.milagritoapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pitahaya.milagritoapp, PID: 28690
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source:0)
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:0)
        at com.lyokone.location.LocationPlugin.<init>(LocationPlugin.java:75)
        at com.lyokone.location.LocationPlugin.registerWith(LocationPlugin.java:204)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:35)
        at com.pitahaya.milagritoapp.MainActivity.onCreate(MainActivity.java:12)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.pitahaya.milagritoapp-u14Dl6eec5L4GmHlIXGlqg==/base.apk"],nativeLibraryDirectories=[/data/app/com.pitahaya.milagritoapp-u14Dl6eec5L4GmHlIXGlqg==/lib/x86, /data/app/com.pitahaya.milagritoapp-u14Dl6eec5L4GmHlIXGlqg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source:0) 
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:0) 
        at com.lyokone.location.LocationPlugin.<init>(LocationPlugin.java:75) 
        at com.lyokone.location.LocationPlugin.registerWith(LocationPlugin.java:204) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:35) 
        at com.pitahaya.milagritoapp.MainActivity.onCreate(MainActivity.java:12) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by jamilex** [comment]
I got the same. The app doesn't even start.

It happens for me if I try to use it with the following plugins: flutter_map ^0.0.1 or geolocation 0.2.1

**Comment by Lyokone** [comment]
Should be solved with 1.3.2
