### ISSUE TITLE
AndroidManifest.xml error - app crashes at startup

### ISSUE THREAD

**Issue by AlexBacich** [Lyokone/flutterlocation#403]
**Describe the bug**

Getting started guide says this: With Flutter 1.12, all the dependencies are automatically added to your project. If your project was created before Flutter 1.12, you may need to follow this.

I did, but it is still failing at startup:

```
2020-08-13 10:40:59.108 2515-2588/com.example.flutter_plugin_playground E/AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
    Process: com.example.flutter_plugin_playground, PID: 2515
    java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:17)
        at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5)
        at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source:94)
        at com.google.android.gms.common.internal.GoogleApiAvailabilityCache.getClientAvailability(Unknown Source:23)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.connect(Unknown Source:216)
        at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source:47)
        at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(Unknown Source:173)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Expected behavior**
Should be able to use app without 

**Tested on:**
 - Android, API Level  28 real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by AlexBacich** [comment]
I solved the issue by doing 2 things: 

1. Adding GMS services setup as described here: https://developers.google.com/android/guides/setup
2. Added this into manifest under application tag:  
```
<meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
```

Probably information should be added into readme.
