### ISSUE TITLE
Crash when using in combination with firebase_messaging

### ISSUE THREAD

**Issue by tolotrasamuel** [Lyokone/flutterlocation#405]
**Describe the bug**
When using firebase_messaging, you need to to add [your own Application class that implements PluginRegistrantCallback](https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages). However, this causes WiFiFlutter to crash with the following trace:

**Expected behavior**
No crash

**Tested on:**
 - Android, API Level 28 real device

**Other plugins:**
  - firebase_messaging

**Additional logs**

 java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference
E/AndroidRuntime(17433): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3817)
E/AndroidRuntime(17433): 	at android.app.ActivityThread.access$2100(ActivityThread.java:221)
E/AndroidRuntime(17433): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
E/AndroidRuntime(17433): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17433): 	at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(17433): 	at android.app.ActivityThread.main(ActivityThread.java:7224)
E/AndroidRuntime(17433): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17433): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(17433): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
E/AndroidRuntime(17433): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.app.Activity.getMainLooper()' on a null object reference
E/AndroidRuntime(17433): 	at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.1.0:50)
E/AndroidRuntime(17433): 	at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source)
E/AndroidRuntime(17433): 	at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source)
E/AndroidRuntime(17433): 	at com.lyokone.location.FlutterLocation.setActivity(FlutterLocation.java:106)
E/AndroidRuntime(17433): 	at com.lyokone.location.LocationPlugin.registerWith(LocationPlugin.java:37)
E/AndroidRuntime(17433): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:32)
E/AndroidRuntime(17433): 	at com.exampe.myapp.Application.registerWith(Application.java:18)
E/AndroidRuntime(17433): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:164)
E/AndroidRuntime(17433): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:77)
E/AndroidRuntime(17433): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3807)
``` shell
some logs
```

**Comment by tolotrasamuel** [comment]
Any update on this?
