### ISSUE TITLE
removeLocationUpdates NullPointerException

### ISSUE THREAD

**Issue by j05u3** [Lyokone/flutterlocation#460]
**Describe the bug**
A crash

**Expected behavior**
Not crash

**Tested on:**
 - Android, API 30 Google Pixel 2

**Additional logs**

``` shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.removeLocationUpdates(com.google.android.gms.location.LocationCallback)' on a null object reference
       at com.lyokone.location.FlutterLocation$2.onLocationResult(FlutterLocation.java:250)
       at com.google.android.gms.internal.location.zzau.notifyListener(zzau.java:4)
       at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(ListenerHolder.java:18)
       at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(ListenerHolder.java:6)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I have an add with flutter in mode add-to-app (that is, flutter was added to an existing native app) and I change back and fort from flutter and native activities, that is why I guess I receive this kind of crashes.

In this case maybe just a non-null check on mFusedLocationClient would do it I guess?

**Comment by Lyokone** [comment]
Thanks for the issue report, a PR is underway to solve this :)
