### ISSUE TITLE
Activity Not null exception in LocationPlugin class when integrating firebase library

### ISSUE THREAD

**Issue by Gaurav128** [Lyokone/flutterlocation#474]
When trying to integrate firebase core with flutter location It is throwing not null exception after providing location access and moving to native side. 

We are using flutter as a module and after providing location access when we move to native android screen it crashes in deinitialize of LocationPlugin class giving activity can't be null. Without firebase dependency it is working fine.

It shouldn't throw exception as it is working fine independently.

Tested on
 - One Plus 6 Android Version 10

``` shell
2021-01-07 09:41:45.086 11181-11181/com.onechannel E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.onechannel, PID: 11181
    java.lang.RuntimeException: Unable to destroy activity {com.onechannel/io.flutter.embedding.android.FlutterFragmentActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5058)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5087)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter activity
        _at com.lyokone.location.FlutterLocationService.setActivity(Unknown Source:2)
        at com.lyokone.location.LocationPlugin.deinitialize(LocationPlugin.java:120)
        at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
        at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java:68)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.detachFromActivity(FlutterEnginePluginRegistry.java:346)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:506)_
        at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:645)
        at androidx.fragment.app.Fragment.performDetach(Fragment.java:2839)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1034)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2644)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:329)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:366)
        at android.app.Activity.performDestroy(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1353)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5043)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5087) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```

**Comment by sderungs99** [comment]
This might be the same issue as #472?

**Comment by Lyokone** [comment]
Hi, let me know if it still happening on the 4.2.0 :)
