### ISSUE TITLE
Xiaomi crashes with 'Parameter specified as non-null is null'

### ISSUE THREAD

**Issue by maerlynflagg** [Lyokone/flutterlocation#482]
**Describe the bug**
a user described, that he started the app and it crashes with exception stack. the issue is a forgotten parameter.  i give you all information i got.

**Expected behavior**
Plugin should not crash the app.

**Tested on:**
 - Xiaomi MI9T Smartphone
 - Android Version is unknown, but default is Android 9
 - `location: ^3.2.1`
 - `flutter 1.22.5`

**Additional logs**

this log is from 

``` 
java.lang.RuntimeException: Unable to destroy activity {xxx/xxx.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method h.p.b.c.d, parameter activity 
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5034) 
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5063) 
at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044) 
at android.os.Handler.dispatchMessage(Handler.java:107) 
at android.os.Looper.loop(Looper.java:224) 
at android.app.ActivityThread.main(ActivityThread.java:7560) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method h.p.b.c.d, parameter activity 
at com.lyokone.location.FlutterLocationService.a(Unknown Source:2) 
at com.lyokone.location.b.c(Unknown Source:51) 
at com.lyokone.location.b.d(Unknown Source:0) 
at com.lyokone.location.b.a(Unknown Source:0) 
at io.flutter.embedding.engine.c.c(Unknown Source:52) 
at io.flutter.embedding.android.d.d(Unknown Source:58) 
at io.flutter.embedding.android.h.f0(Unknown Source:5) 
at androidx.fragment.app.Fragment.n0(Unknown Source:3) 
at androidx.fragment.app.j.a(Unknown Source:1184) 
at androidx.fragment.app.j.l(Unknown Source:93) 
at androidx.fragment.app.j.a(Unknown Source:42) 
at androidx.fragment.app.j.d(Unknown Source:4) 
at androidx.fragment.app.j.i(Unknown Source:7) 
at androidx.fragment.app.f.c(Unknown Source:4) 
at androidx.fragment.app.d.onDestroy(Unknown Source:5) 
at android.app.Activity.performDestroy(Activity.java:8180) 
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342) 
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5019) 
... 11 more 
```

**Comment by matt39** [comment]
I have the same crash with the same plugin version and Android 8.0.

**Comment by AleksandrOleynik** [comment]
I have the same crash with the same plugin version and Android 8.1.0

**Comment by danielgomezrico** [comment]
Duplicated from https://github.com/Lyokone/flutterlocation/issues/466

**Comment by maerlynflagg** [comment]
Closed cause duplicated.
