### ISSUE TITLE
1.3.3 Works with API26/27 but fatal exception with API21/25 getSpeedAccuracyMetersPerSecond

### ISSUE THREAD

**Issue by JohnAherne** [Lyokone/flutterlocation#49]
The log is below for the exception.

It looks like this function was added in 1.3.1. But not sure how significant that is
```
[        ] D/AndroidRuntime( 3274): Shutting down VM
[        ] E/AndroidRuntime( 3274): FATAL EXCEPTION: main
[        ] E/AndroidRuntime( 3274): Process: com.example.gpstest3, PID: 3274
[        ] E/AndroidRuntime( 3274): java.lang.NoSuchMethodError: No virtual method getSpeedAccuracyMetersPerSecond()F in class Landroid/location/Location; or its super classes (declaration of 'android.location.Location' appears in /system/framework/framework.jar)
[        ] E/AndroidRuntime( 3274):     at com.lyokone.location.LocationPlugin$2.onLocationResult(LocationPlugin.java:139)
[        ] E/AndroidRuntime( 3274):     at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source)
[        ] E/AndroidRuntime( 3274):     at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source)
[        ] E/AndroidRuntime( 3274):     at com.google.android.gms.common.api.internal.ListenerHolder$zza.handleMessage(Unknown Source)
[        ] E/AndroidRuntime( 3274):     at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] E/AndroidRuntime( 3274):     at android.os.Looper.loop(Looper.java:135)
[        ] E/AndroidRuntime( 3274):     at android.app.ActivityThread.main(ActivityThread.java:5221)
[        ] E/AndroidRuntime( 3274):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 3274):     at java.lang.reflect.Method.invoke(Method.java:372)
[        ] E/AndroidRuntime( 3274):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
[        ] E/AndroidRuntime( 3274):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
[        ] D/        ( 3274): HostConnection::get() New Host Connection established 0xac6f6100, tid 3390
[        ] D/EGL_emulation( 3274): eglMakeCurrent: 0xaf915040: ver 3 1
[  +22 ms] I/Process ( 3274): Sending signal. PID: 3274 SIG: 9
[  +86 ms] TimeoutException after 0:00:00.250000: Future not completed
[   +9 ms] "flutter run" took 105,130ms.
```

**Comment by JohnAherne** [comment]
Looks like someone addressed this a few days ago. Not yet published to pub.

**Comment by Lyokone** [comment]
Published right now, sorry for the delay !
