### ISSUE TITLE
Plugin crashes and stops responding on some devices

### ISSUE THREAD

**Issue by SilverCrow11** [Lyokone/flutterlocation#493]
**Describe the Bug**
App's location module(plugin) isn't returning any information on some mobile devices. Tested on Xiaomi Redmi note 8 pro, and some other real devices where this occurred. Normally when installed via Android studios, the apk-debug works perfectly fine. But when apk-release is installed it works for First time when app starts, and then when restarted, gives these errors.

**Expected behavior**
This app was designed to return longitude and latitude of mobile's current location on start of the app, but isn't able to do so. It was working perfectly fine when pub version was ^3.0.0. But started giving error when I upgraded it to ^3.2.1 for background service.

**Tested on**
Emulators, API 27 till 30, works perfectly fine.
On real devices, doesn't gives these error on some devices that have API 29 or 30.

**List of other plugins that might affect it**
I don't really know if these plugins might interfere or not, but here's the list:
  sensors: ^0.4.2+5
  provider: ^4.0.0
  location: 3.2.1
  flutter_compass: ^0.4.3
  intl: ^0.16.1
  flutter_map: ^0.10.1+1
  sqflite: any
  path_provider: any
  permission_handler: ^5.0.1
  flutter_shapes: ^0.2.1
  flutter_plot: ^0.0.4
  flushbar: ^1.10.4
  flutter_beep: ^0.2.0
  battery_indicator: ^0.0.5
  date_time_format: ^1.1.0
  shared_preferences: ^0.5.12+4
  flutter_settings_screens: ^0.2.1+1
  vibration: ^1.7.3
  torch_compat: ^1.0.2

**Additional Logs**
Here is the verbose:

```
E/flutter (22420): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(CHANGE_SETTINGS_ERROR, An unexcepted error happened during location settings change:Attempt to read from field 'android.util.SparseArray com.lyokone.location.a.l' on a null object reference, null, null)
E/flutter (22420): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter (22420): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): #2      MethodChannelLocation.changeSettings (package:location_platform_interface/src/method_channel_location.dart:49)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): 
I/flutter (22420): 
E/flutter (22420): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Attempt to write to field 'e.a.c.a.j$d com.lyokone.location.a.j' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 'e.a.c.a.j$d com.lyokone.location.a.j' on a null object reference
E/flutter (22420): 	at com.lyokone.location.c.b(Unknown Source:2)
E/flutter (22420): 	at com.lyokone.location.c.a(Unknown Source:124)
E/flutter (22420): 	at e.a.c.a.j$a.a(Unknown Source:17)
E/flutter (22420): 	at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
E/flutter (22420): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (22420): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (22420): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (22420): 	at android.os.Looper.loop(Looper.java:165)
E/flutter (22420): 	at android.app.ActivityThread.main(ActivityThread.java:6861)
E/flutter (22420): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22420): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (22420): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (22420): )
E/flutter (22420): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter (22420): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:359)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): #3      MethodChannelLocation.getLocation (package:location_platform_interface/src/method_channel_location.dart:81)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): #4      _MyHomePageState.setInitialLocation (package:sensor_check_app/main.dart:214)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): 

```

**Comment by SilverCrow11** [comment]
Additional Comment :
`E/flutter (22420): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(CHANGE_SETTINGS_ERROR, An unexcepted error happened during location settings change:Attempt to read from field 'android.util.SparseArray com.lyokone.location.a.l' on a null object reference, null, null)
E/flutter (22420): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582)
E/flutter (22420): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): #2      MethodChannelLocation.changeSettings (package:location_platform_interface/src/method_channel_location.dart:49)
E/flutter (22420): <asynchronous suspension>
E/flutter (22420): `

This error seems to be from the location.changeSetting. So for time being, I disabled it.
