### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted | DartMessenger | FlutterLocation

### ISSUE THREAD

**Issue by sanjaymajoka** [Lyokone/flutterlocation#512]
**Receiving java.lang.IllegalStateException: Reply already submitted in Flutter Location.java. This is very frequent crash appears in Crashliytics logs.**

_Didn't find any solution, below is crash logs:_

Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:35)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:14)
       at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:43)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:25)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:15)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:51)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:2)
       at android.app.Activity.dispatchActivityResult(Activity.java:8300)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by kleyos** [comment]
I am always getting this error when refusing to turn on the location. It calls app crash `java.lang.IllegalStateException: Reply already submitted`. it pretty critical issue

**Comment by Lyokone** [comment]
Hi, let me know if it is still happening with 4.2.0, a bunch of issue on Android were resolved :)
