### ISSUE TITLE
Flutter location throw error when i run it on the web (chrome) and it don't get Lat and Long

### ISSUE THREAD

**Issue by TalebRafiepour** [Lyokone/flutterlocation#526]
**Describe the bug**
When I want to get a location position in the web it throw error => Error: [object GeolocationPositionError]

**Expected behavior**

**Tested on:**
 - Chrome

**Other plugins:**
<img width="900" alt="Screen Shot 2021-03-08 at 10 47 39" src="https://user-images.githubusercontent.com/40627325/110287440-c4c9a400-7ffb-11eb-803a-b0d3246200a9.png">

  location: ^4.0.2
  url_launcher: ^6.0.2

**Additional logs**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.14.6 18G8022 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.8.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

``` shell
💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:51805/k-FnYHSTD0M=/ws
Error: [object GeolocationPositionError]


    at Object.createErrorWithStack (http://localhost:51765/dart_sdk.js:5045:12)
    at Object._rethrow (http://localhost:51765/dart_sdk.js:37477:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51765/dart_sdk.js:37473:13)
    at Object._microtaskLoop (http://localhost:51765/dart_sdk.js:37333:13)
    at _startMicrotaskLoop (http://localhost:51765/dart_sdk.js:37339:13)
    at http://localhost:51765/dart_sdk.js:33110:9
```

**Comment by Lyokone** [comment]
Hi, is it related to #545 ?
