### ISSUE TITLE
PlatformException(error, Attempt to write to field 'd.a.c.a.c$b com.lyokone.location.a.h' on a null object reference, null, null)

### ISSUE THREAD

**Issue by neoacevedo** [Lyokone/flutterlocation#541]
**Describe the bug**
 `PlatformException(error, Attempt to write to field 'd.a.c.a.c$b com.lyokone.location.a.h' on a null object reference, null, null)`
It happens when I run the code inside Workmanager. 

```
Workmanager.executeTask((taskName, inputData) async {
    switch (taskName) {
      case "locationupdates":
          _locationSubscription =
                    _location.onLocationChanged.listen((currentLocation) {
                 ...
          });
          break;
});
```

**Expected behavior**
The idea is the code can run without to kill in background whatever if the app is in foreground or background. Workmanager works good if I don't set any location plugin code inside.

**Tested on:**
 - Android, API Level 26, real device

**Other plugins:**
 - Workmanager

**Additional logs**
<details>
<summary>log</summary>

``` shell
Launching lib/main.dart on GT N5110 in debug mode...
Plugin project :location_web not found. Please update settings.gradle.
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
D/FlutterLocationService(17120): Creating service.
D/FlutterLocationService(17120): Binding to location service.
Connecting to VM Service at ws://127.0.0.1:44557/qI_VNNVd8Jo=/ws
I/d0      (17120): Making Creator dynamically
I/DynamiteModule(17120): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203112999
I/DynamiteModule(17120): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203112999
V/DynamiteModule(17120): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/System  (17120): ClassLoader referenced unknown path:
D/ApplicationLoaders(17120): ignored Vulkan layer search path /data/app/com.google.android.gms-1/lib/arm:/data/app/com.google.android.gms-1/base.apk!/lib/armeabi-v7a:/data/app/com.google.android.gms-1/split_config.es.apk!/lib/armeabi-v7a for namespace 0x40076090
W/System  (17120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000008b/n/armeabi-v7a
W/System  (17120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000008b/n/armeabi
I/Google Maps Android API(17120): Google Play services client version: 12451000
I/Google Maps Android API(17120): Google Play services package version: 210613015
I/flutter (17120): DataConnectionCheckerDataConnectionStatus.connected
W/System  (17120): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
I/flutter (17120): zoom: 17.0
I/flutter (17120): Iniciando locationupdates
E/EventChannel#lyokone/locationstream(17120): Failed to open event stream
E/EventChannel#lyokone/locationstream(17120): java.lang.NullPointerException: Attempt to write to field 'd.a.c.a.c$b com.lyokone.location.a.h' on a null object reference
E/EventChannel#lyokone/locationstream(17120): 	at com.lyokone.location.f.a(:50)
E/EventChannel#lyokone/locationstream(17120): 	at d.a.c.a.c$c.b(:188)
E/EventChannel#lyokone/locationstream(17120): 	at d.a.c.a.c$c.a(:167)
E/EventChannel#lyokone/locationstream(17120): 	at io.flutter.embedding.engine.e.b.a(:85)
E/EventChannel#lyokone/locationstream(17120): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:692)
E/EventChannel#lyokone/locationstream(17120): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#lyokone/locationstream(17120): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/EventChannel#lyokone/locationstream(17120): 	at android.os.Looper.loop(Looper.java:136)
E/EventChannel#lyokone/locationstream(17120): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/EventChannel#lyokone/locationstream(17120): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#lyokone/locationstream(17120): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/EventChannel#lyokone/locationstream(17120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
I/WM-WorkerWrapper(17120): Worker result SUCCESS for Work [ id=e2790e7c-b585-4213-87cf-fffa18eb31ab, tags={ be.tramckrijte.workmanager.BackgroundWorker } ]
W/DynamiteModule(17120): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(17120): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule(17120): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/System  (17120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000008a/n/armeabi-v7a
W/System  (17120): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000008a/n/armeabi

[38;5;248m════════ Exception caught by services library ══════════════════════════════════[39;49m
[38;5;244mThe following PlatformException was thrown while activating platform stream on channel lyokone/locationstream:[39;49m
PlatformException(error, Attempt to write to field 'd.a.c.a.c$b com.lyokone.location.a.h' on a null object reference, null, null)

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244m#1      MethodChannel._invokeMethod[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m#2      MethodChannel.invokeMethod[39;49m
[38;5;244m#3      EventChannel.receiveBroadcastStream.<anonymous closure>[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
E/flutter (17120): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: SocketException: Failed host lookup: 'usuarios-dev.tuttocol.com' (OS Error: No address associated with hostname, errno = 7)
E/flutter (17120):
I/art     (17120): Background partial concurrent mark sweep GC freed 101943(4MB) AllocSpace objects, 68(4MB) LOS objects, 40% free, 9MB/15MB, paused 1.505ms total 114.064ms
```

</details>

**Comment by Lyokone** [comment]
I thanks for the report, it's a known limitation since this package relies on an activity. Check the `enableBackgroundMode` method to see if it's okay for you :)

**Comment by diegohzea** [comment]
@neoacevedo found any solution/workaround?
