### ISSUE TITLE
Failing on web in release mode

### ISSUE THREAD

**Issue by yahu1031** [Lyokone/flutterlocation#545]
**Describe the bug**
This package works perfectly fine in mentioned device when it is debug mode. but when it comes in release it fails.

**Expected behavior**
It must fetch the location coordinates.

**Attained behavior**
![image](https://user-images.githubusercontent.com/35523357/114296364-a823fe80-9ac8-11eb-8525-3c35a6217e41.png)

**Tested on:**
 - Chrome, Edge

**Additional logs**
chrome dev tools

```shell
Uncaught UnimplementedError
    at Object.b (http://localhost:1031/main.dart.js:3662:3)
    at CD.oH (http://localhost:1031/main.dart.js:58884:23)
    at http://localhost:1031/main.dart.js:58664:20
    at a6A.a (http://localhost:1031/main.dart.js:5226:71)
    at a6A.$2 (http://localhost:1031/main.dart.js:29270:23)
    at Object.T (http://localhost:1031/main.dart.js:5212:19)
    at wL.n2 (http://localhost:1031/main.dart.js:58667:10)
    at wL.aR (http://localhost:1031/main.dart.js:58657:20)
    at eV.vW (http://localhost:1031/main.dart.js:53046:8)
    at eV.fa (http://localhost:1031/main.dart.js:53002:6)
    
Uncaught TypeError: t1.get$coords is not a function
    at LocationWebPlugin._toLocationData$1 (location_web.dart:103)
    at location_web.dart:38
    at _wrapJsFunctionForAsync_closure.$protected (async_patch.dart:316)
    at _wrapJsFunctionForAsync_closure.call$2 (async_patch.dart:341)
    at _awaitOnObject_closure.call$1 (async_patch.dart:292)
    at _RootZone.runUnary$2$2 (zone.dart:1612)
    at _RootZone.runUnary$2 (zone.dart:1611)
    at _Future__propagateToListeners_handleValueCallback.call$0 (future_impl.dart:118)
    at Object._Future__propagateToListeners (future_impl.dart:733)
    at _Future._completeWithValue$1 (future_impl.dart:539)
```

It doesn't give any errors on debug console log.

**Comment by matthewtsmith** [comment]
Found this related issue in the Dart SDK.

https://github.com/dart-lang/sdk/issues/45562

Temporary solution is to not build with null safety ( --no-sound-null-safety ) until this is fixed in the Dart SDK.

**Comment by Lyokone** [comment]
Thanks for the temporary solution, wasn't able to find it 👍
