### ISSUE TITLE
Can not compile Version 4.1.1

### ISSUE THREAD

**Issue by ride4sun** [Lyokone/flutterlocation#566]
**Describe the bug**

When I compile with the latest version I get the following compile error :
```
C:\Users\ride4\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\location-4.1.1\android\src\main\java\com\lyokone\location\FlutterLocationService.k
t: (73, 33): Unresolved reference: createNotificationChannel
[   +6 ms] FAILURE: Build failed with an exception.
[   +7 ms] * What went wrong:
[   +1 ms] Execution failed for task ':location:compileDebugKotlin'.
[   +1 ms] > Compilation error. See log for more details
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 36s
[ +626 ms] Running Gradle task 'assembleDebug'... (completed in 37.7s)
[   +6 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +3 ms] "flutter run" took 39,523ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +157 ms] ensureAnalyticsSent: 151ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +3 ms] exiting with code 1
```

flutter doctor:
```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code, 32-bit edition (version 1.51.1)
[√] Connected device (3 available)
```

**Comment by Lyokone** [comment]
Hi, I have no issue compiling release app with my plugin.
Which version of Gradle are you using ?
