### ISSUE TITLE
PlatformException

### ISSUE THREAD

**Issue by 2math** [Lyokone/flutterlocation#570]
**Describe the bug**
Hi and thanks for this great plugin. 

I have a problem using it with a foreground service plugin(https://pub.dev/packages/android_long_task)
When I use it in the app is working great, but when I use it in the callback from the foreground service it crashes with null pointer.
I see the foreground service is sending data to a global function  "serviceMain" as
```
  engine = FlutterEngine(applicationContext)

  val entrypoint = DartEntrypoint("lib/main.dart", "serviceMain")

  engine!!.dartExecutor.executeDartEntrypoint(entrypoint)

//here I tried to register the plugin again, but I can see in the logs a message that the plugin is already registered with this 
//engine, so the engine is registered but some how the FlutterLocation is null
//      AndroidLongTaskPlugin.pluginRegistryCallback.invoke(engine!!)

    channel = MethodChannel(engine!!.dartExecutor.binaryMessenger, channel_name)

    channel!!.setMethodCallHandler { call, result -> ...
```
Thanks in advance!

**Tested on:**
Pixel 3a XL android 11

**Other plugins:**
https://pub.dev/packages/android_long_task

**Additional logs**
```
E/MethodChannel#lyokone/location(12219): Failed to handle method call
E/MethodChannel#lyokone/location(12219): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.lyokone.location.FlutterLocation.checkPermissions()' on a null object reference
E/MethodChannel#lyokone/location(12219): 	at com.lyokone.location.MethodCallHandlerImpl.onHasPermission(MethodCallHandlerImpl.java:123)
E/MethodChannel#lyokone/location(12219): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:41)
E/MethodChannel#lyokone/location(12219): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#lyokone/location(12219): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#lyokone/location(12219): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:738)
E/MethodChannel#lyokone/location(12219): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#lyokone/location(12219): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#lyokone/location(12219): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#lyokone/location(12219): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/MethodChannel#lyokone/location(12219): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#lyokone/location(12219): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#lyokone/location(12219): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Lyokone** [comment]
Hi :) Happy this plugin can help you,
I don't know about android_long_task, but according to their README
```
Android Activities and Services do not in the same process. that is the reason why when use closes your app and your app's process gets killed by the system your code in foreground service will still run. because your flutter app code runs in an Activity which has a separate process from your Foreground Service
```
It's normal that my plugin does not work.

What is your use case ? Does the `enableBackgroundMode` function can help you ?

**Comment by 698373862** [comment]
This is still a major issue, plugin doesn't work when trying to use with foreground services

**Comment by moazelsawaf** [comment]
Still facing the issue ..

**Comment by musamaashraf** [comment]
I am also facing this issue
