### ISSUE TITLE
App crashes when I refuse to enable Location.

### ISSUE THREAD

**Issue by Velek** [Lyokone/flutterlocation#585]
If I start the app with Location disable and I tap "No Thanks" when asked to enable it, the app will crash.

D/AndroidRuntime( 2380): Shutting down VM
E/AndroidRuntime( 2380): FATAL EXCEPTION: main
E/AndroidRuntime( 2380): Process: com.velekhacks.globe_trotter, PID: 2380
E/AndroidRuntime( 2380): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent { (has extras) }} to activity {com.velekhacks.globe_trotter/com.velekhacks.globe_trotter.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2380): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
E/AndroidRuntime( 2380): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4441)
E/AndroidRuntime( 2380): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime( 2380): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
E/AndroidRuntime( 2380): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 2380): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 2380): 	at android.app.ActivityThread.main(ActivityThread.java:6710)
E/AndroidRuntime( 2380): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2380): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime( 2380): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
E/AndroidRuntime( 2380): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2380): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/AndroidRuntime( 2380): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
E/AndroidRuntime( 2380): 	at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:182)
E/AndroidRuntime( 2380): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:739)
E/AndroidRuntime( 2380): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime( 2380): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:677)
E/AndroidRuntime( 2380): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:624)
E/AndroidRuntime( 2380): 	at android.app.Activity.dispatchActivityResult(Activity.java:7240)
E/AndroidRuntime( 2380): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4394)

**Comment by MohamadSobhy** [comment]
I have the same issue with location 4.3.0. Also, I noticed that the dialog appears twice to ask me to enable location services. At the beginning if I accepted or refused to enable location service the dialog appear again to ask me to enable the service and the app crashes when I accept or refuse it again.

**Comment by melikbozkurt** [comment]
Any update here? I am having the same issue.

**Comment by Velek** [comment]
On 11/21/22 1:14 AM, melikbozkurt wrote:
>
> Any update here? I am having the same issue.
>
Message ID: ***@***.***

I had forgotten about this issue.  It's not good news to me that it 
still exists.

**Comment by shahpasandar** [comment]
I'm also have this on `location: ^4.4.0`
