### ISSUE TITLE
Location permissions being prompted twice.

### ISSUE THREAD

**Issue by pneves001** [Lyokone/flutterlocation#62]
Hi, I'm having a problem with this plugin asking for permission multiple times when we install it. But then crashes after we respond to the second prompt.  The following is the stack trace I get. 

FATAL EXCEPTION: main
E/AndroidRuntime(23557): Process:  PID: 23557
E/AndroidRuntime(23557): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(23557):        at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:148)
E/AndroidRuntime(23557):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(23557):        at com.lyokone.location.LocationPlugin$3.onSuccess(LocationPlugin.java:235)
E/AndroidRuntime(23557):        at com.lyokone.location.LocationPlugin$3.onSuccess(LocationPlugin.java:220)
E/AndroidRuntime(23557):        at com.google.android.gms.tasks.zzn.run(Unknown Source)
E/AndroidRuntime(23557):        at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime(23557):        at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime(23557):        at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(23557):        at android.app.ActivityThread.main(ActivityThread.java:5729)
E/AndroidRuntime(23557):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23557):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
E/AndroidRuntime(23557):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by timtraversy** [comment]
Can you share the code you've written to request permission?

**Comment by pneves001** [comment]
thank you for getting back to me, however, I've actually decided to use a different plugin.
