### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.lyokone.location.FlutterLocationService$a

### ISSUE THREAD

**Issue by stx** [Lyokone/flutterlocation#620]
Have seen this error twice on our production app.

Galaxy Z Fold2 5G
Android Version: 11

```
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.lyokone.location.FlutterLocationService$a
       at com.lyokone.location.LocationPlugin$1.onServiceConnected(LocationPlugin.java:24)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by talent-apps** [comment]
We also see this issue in production:
```
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.lyokone.location.FlutterLocationService$b
       at com.lyokone.location.LocationPlugin$1.onServiceConnected(LocationPlugin.java:18)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
It happens exclusively on **devices with Android 11**.

**Comment by arvinsen** [comment]
01-29 18:51:18.864  7588  7588 E DEBUG   : java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.lyokone.location.FlutterLocationService$a
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at com.lyokone.location.g$a.onServiceConnected(Unknown Source:24)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at android.os.Handler.handleCallback(Handler.java:938)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at android.os.Looper.loop(Looper.java:246)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at android.app.ActivityThread.main(ActivityThread.java:8633)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at java.lang.reflect.Method.invoke(Native Method)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
01-29 18:51:18.864  7588  7588 E DEBUG   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
01-29 18:51:18.864  7588  7588 E DEBUG   : Back traces ends.

i am also got this problem on samsung SM-G781N  android 11, i'm just add this pub package in my app and do nothing in native java code.
