### ISSUE TITLE
In android 11 error in getting location in real device

### ISSUE THREAD

**Issue by alihassan143** [Lyokone/flutterlocation#661]
```
E/MethodChannel#lyokone/location(26758): 	at android.os.MessageQueue.next(MessageQueue.java:339)
E/MethodChannel#lyokone/location(26758): 	at android.os.Looper.loop(Looper.java:199)
E/MethodChannel#lyokone/location(26758): 	at android.app.ActivityThread.main(ActivityThread.java:8288)
E/MethodChannel#lyokone/location(26758): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#lyokone/location(26758): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/MethodChannel#lyokone/location(26758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
E/flutter (26758): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference
E/flutter (26758): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:117)
E/flutter (26758): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
E/flutter (26758): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (26758): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (26758): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (26758): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26758): 	at android.os.MessageQueue.next(MessageQueue.java:339)
E/flutter (26758): 	at android.os.Looper.loop(Looper.java:199)
E/flutter (26758): 	at android.app.ActivityThread.main(ActivityThread.java:8288)
E/flutter (26758): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26758): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/flutter (26758): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
E/flutter (26758): )
E/flutter (26758): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter (26758): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
E/flutter (26758): <asynchronous suspension>
E/flutter (26758): #2      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:356
E/flutter (26758): <asynchronous suspension>
E/flutter (26758): #3      MethodChannelLocation.getLocation
package:location_platform_interface/src/method_channel_location.dart:87
E/flutter (26758): <asynchronous suspension>
E/flutter (26758):


i am getting error in getting  location in background flutter
and when app is open also getting the same error

```

**Comment by vinoth028** [comment]
Any solution for the above issue

**Comment by tehsunnliu** [comment]
same error
