### ISSUE TITLE
LocationPlugin.dispose crashes on configuration change handling

### ISSUE THREAD

**Issue by sergey-triputsco** [Lyokone/flutterlocation#664]
Plugin crashes on handling Android configuration change.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.h()' on a null object reference
       at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:20)
       at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java)
       at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges(FlutterEngineConnectionRegistry.java:57)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:48)
       at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:7)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:11)
```

Crash happens on the next OS versions Android 9, 10, 11, 12.

**Comment by lynnscode** [comment]
I have the error too。 location version:4.3.0
E/AndroidRuntime(20904): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(20904): 	at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:117)
E/AndroidRuntime(20904): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)
E/AndroidRuntime(20904): 	at com.lyokone.location.LocationPlugin.onDetachedFromActivityForConfigChanges(LocationPlugin.java:74)
E/AndroidRuntime(20904): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivityForConfigChanges(FlutterEngineConnectionRegistry.java:375)
E/AndroidRuntime(20904): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:630)
E/AndroidRuntime(20904): 	at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:622)
E/AndroidRuntime(20904): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:643)
E/AndroidRuntime(20904): 	at android.app.Activity.performDestroy(Activity.java:8319)
E/AndroidRuntime(20904): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1376)
E/AndroidRuntime(20904): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5441)
E/AndroidRuntime(20904): 	... 15 more

**Comment by metajet98** [comment]
same issue on version 4.3.0

**Comment by Lyokone** [comment]
Hello, can you try the latest [5.0.0](https://pub.dev/packages/location/versions/5.0.0-dev.7) to see if it's still happen?

**Comment by Lyokone** [comment]
The Android plugin was rewritten in Kotlin for 9.0.0 and the teardown in `dispose`/`detachActivity` is now null safe, so this NullPointerException on configuration changes should be gone.

https://pub.dev/packages/location/versions/9.0.0

Closing as fixed. Please reopen if you still hit it on 9.0.0.
