### ISSUE TITLE
Crash on location v4.2.3 and v4.3.0

### ISSUE THREAD

**Issue by alicehanina** [Lyokone/flutterlocation#669]
This exception commonly occurs on Xiaomi and Samsung devices, android 10-11. We have android app(single activity) with integrated flutter in it. We used v4.3.0 when we first met this issue. We tried to downgrade it to 4.2.3 but it doesn't help

Fatal Exception: java.lang.NullPointerException
       at com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener(FlutterLocationService.java:20)
       at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:20)
       at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:20)
       at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.c(FlutterEngineConnectionRegistry.java:44)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:8)
       at io.flutter.embedding.android.FlutterFragment.detachFromFlutterEngine(FlutterFragment.java:21)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(FlutterActivityAndFragmentDelegate.java:21)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:21)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:21)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:4)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:6)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:8)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:84)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:4)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:4)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:4)
       at androidx.appcompat.app.AppCompatDelegateImpl.onStart(AppCompatDelegateImpl.java)
       at MainActivity.onStart(MainActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8231)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3861)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by YassineChe** [comment]
Same issue!!
Any improvement yet!!


(I will be back to you if i found anything)

**Comment by YassineChe** [comment]
Hello, after a long nightmare and googling a lot i couldn't find anything.
But.. I realized  that even the permission is granted you have to set the GPS on!
So what i did in my situation is check the the location service is granted then check the GPS is ON.

In my case i'm use a Stream to broadcast the real time coordinate i wrapped the StreamController with GPS Checker, its provided by Location library

Here a snapshot :

    location.requestPermission().then((locationPermission) async {
      if (locationPermission == PermissionStatus.granted) {
        if (await location.serviceEnabled()) { //GPS is ON
          location.onLocationChanged.listen((locationValue) {
            streamLocationController.add(
              Coordinate(
                lat: locationValue.latitude,
                lng: locationValue.longitude,
              ),
            );
          });
        } else {
          location.requestService(); //GPS is OFF (WILL PROMPT A DIALOG to turn it (NO,THANKS | OK))
        }
      }
    });

The idea was to prompt to the user a dialog to set GPS on! `location.requestService()` will do the trick

Hope this works for you...
