### ISSUE TITLE
plugin crashing in case of keep approximate location in android 12.

### ISSUE THREAD

**Issue by vineetpandit90** [Lyokone/flutterlocation#690]
When we select to keep approximate location in permission dialog, plugin crashing.
Pls handle android 12 cases in plugin.

**Comment by miketrebilcock** [comment]
I think I'm seeing something similar through crashlytics, I've not been able to reproduce it myself yet:


`Fatal Exception: java.lang.SecurityException: Neither user 10335 nor current process has android.permission.ACCESS_FINE_LOCATION.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
       at android.os.Parcel.createException(Parcel.java:2409)
       at android.os.Parcel.readException(Parcel.java:2392)
       at android.os.Parcel.readException(Parcel.java:2334)
       at android.location.ILocationManager$Stub$Proxy.registerGnssNmeaCallback(ILocationManager.java:1921)
       at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:3012)
       at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:3002)
       at com.android.internal.listeners.ListenerTransportManager.addListener(ListenerTransportManager.java:70)
       at android.location.LocationManager.addNmeaListener(LocationManager.java:2522)
       at android.location.LocationManager.addNmeaListener(LocationManager.java:2503)
       at com.lyokone.location.FlutterLocation.lambda$startRequestingLocation$2(FlutterLocation.java:11)
       at com.lyokone.location.FlutterLocation.lambda$startRequestingLocation$2$FlutterLocation(FlutterLocation.java)
       at com.lyokone.location.-$$Lambda$FlutterLocation$GtSSUe8dBDBBQxv83CuVjKNJ2RM.onSuccess(-.java:4)
       at com.google.android.gms.tasks.zzm.run(zzm.java:25)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

and

`Caused by android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2178)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2206)
	at com.android.server.location.gnss.GnssManagerService.registerGnssNmeaCallback(GnssManagerService.java:177)
	at com.android.server.location.LocationManagerService.registerGnssNmeaCallback(LocationManagerService.java:1018)
	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:854)`

I got the following device information:
![image](https://user-images.githubusercontent.com/1905325/154225484-1b6bcb18-2ac6-4ae3-95dc-4702e7218529.png)


My code is firstly setting high accuracy, then checking/requesting permissions before getting a location. Here's a snippet:

`
void initLocationService() async {
    await _locationService.changeSettings(
      accuracy: LocationAccuracy.high,
      interval: 1000,
    );

    LocationData? location;
    bool serviceEnabled;
    bool serviceRequestResult;

    try {
      serviceEnabled = await _locationService.serviceEnabled();
      if (serviceEnabled) {
        var permission = await _locationService.requestPermission();
        _permission = permission == PermissionStatus.granted;
        if (_permission) {
          location = await _locationService.getLocation();
`

I think it's fine that it errors, but it seems to error in a way that my try block doesn't catch it?

**Comment by awaisabbasaa11** [comment]
Still facing this issue on Android in the latest version (4.4.0) as well, can someone please provide any update on this
