### ISSUE TITLE
get location on background

### ISSUE THREAD

**Issue by liqiang1995** [Lyokone/flutterlocation#724]
My idea is
When App receives the background firebase notification, App gets the current location.

My code is

![image](https://user-images.githubusercontent.com/54995513/168965524-8e31bdb4-12fa-42fb-8c3d-3dfbc903f5d9.png)

But I am getting an error.

E/MethodChannel#lyokone/location(27361): Failed to handle method call
E/MethodChannel#lyokone/location(27361): java.lang.NullPointerException: Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference
E/MethodChannel#lyokone/location(27361): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:117)
E/MethodChannel#lyokone/location(27361): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
E/MethodChannel#lyokone/location(27361): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#lyokone/location(27361): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#lyokone/location(27361): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#lyokone/location(27361): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#lyokone/location(27361): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#lyokone/location(27361): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#lyokone/location(27361): 	at android.os.Looper.loop(Looper.java:237)
E/MethodChannel#lyokone/location(27361): 	at android.app.ActivityThread.main(ActivityThread.java:7971)
E/MethodChannel#lyokone/location(27361): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#lyokone/location(27361): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#lyokone/location(27361): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
I/flutter (27361): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (27361): PlatformException(error, Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference
I/flutter (27361): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:117)
I/flutter (27361): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
I/flutter (27361): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (27361): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
I/flutter (27361): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
I/flutter (27361): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
I/flutter (27361): 	at android.os.Handler.handleCallback(

Do you have an idea to fix this?
Thank you.

**Comment by tehsunnliu** [comment]
Getting the same error and `location.onLocationChanged` is not getting called

**Comment by anushaVinove** [comment]
Any solution for this issue yet?

**Comment by alcampospalacios** [comment]
Any solution for this issue yet?

**Comment by jestebto** [comment]
Same issue here

**Comment by Lyokone** [comment]
Fixed by #1072 (merged): documented that background mode requires the app process to stay alive and can't survive the app being killed/terminated — not achievable by this plugin (or any Flutter plugin) once the process is gone. See the README's Background mode section for the updated guidance and `flutter_background_geolocation` as an alternative for post-termination tracking.
