### ISSUE TITLE
.hasPermission() also requests permission?

### ISSUE THREAD

**Issue by Svegiary** [Lyokone/flutterlocation#727]
**Describe the bug**
When I call `await location.hasPermission();` it actually asks for the permission rather than just checking it.
`await location.requestPermission();` also requests the permission , leading to asking 2 permissions at once. 

**Expected behavior**
When I call `await location.hasPermission();` , I expect it to check if I the permission has been granted and not request it.
Then when I call `await location.requestPermission();` , only then I expect the permission dialog box to be displayed

**Tested on:**
 - Android 12 , Real Pixel 5 , ADB

 

**Full Code Sample:** 
```
class Gmap extends StatefulWidget {
  const Gmap({ Key? key }) : super(key: key);

  @override
  State<Gmap> createState() => _GmapState();

}

class _GmapState extends State<Gmap> {

  String _mapStyle = "";
  late GoogleMapController mapController;
  late Future<LatLng> ull ;
  Location location = Location();
  final LatLng _center = const LatLng(37.983810, 23.727539); 
  LatLng _userLocation = const LatLng(37.983810, 23.727539);


  Future<LatLng> userLocation() async{
    PermissionStatus _permissionGranted;
    bool _serviceEnabled;

    _serviceEnabled = await location.serviceEnabled();
    if (!_serviceEnabled) {
      _serviceEnabled = await location.requestService();
      if (!_serviceEnabled) {
        return _center;
      }
    }

    _permissionGranted = await location.hasPermission(); //it requests permission here
    if (_permissionGranted == PermissionStatus.denied) {
      _permissionGranted = await location.requestPermission()//it requests here again;
      if (_permissionGranted != PermissionStatus.granted) {
        return _center;
      }
    }
    LocationData l = await location.getLocation();
    setState((){
      _userLocation  = LatLng(l.latitude!, l.longitude!);
    });
    return _userLocation;
  }

  void centerLocation(){
    CameraPosition userCamera = CameraPosition(
            target: _userLocation,
            zoom: 14.0,
          );

    CameraUpdate moveTo =  CameraUpdate.newCameraPosition(userCamera);    
    mapController.animateCamera(moveTo);
  }

  void _onMapCreated(GoogleMapController controller) async{
    
    mapController = controller;
    mapController.setMapStyle(_mapStyle);    
    centerLocation();   
  }

  @override
  void initState() {
    super.initState();
    rootBundle.loadString('assets/style.txt').then((string) { 
      _mapStyle = string;
    });
    ull = userLocation();

  }  

  Widget googleMap(userLocation){
  return GoogleMap(
          onMapCreated: _onMapCreated,
          myLocationEnabled:true,
          initialCameraPosition: CameraPosition(
            target: userLocation,
            zoom: 6.0,
          ),
          zoomControlsEnabled: false, //dont show zoom buttons
          compassEnabled: false, 
          
          myLocationButtonEnabled: false,
        );
}


  @override
  Widget build(BuildContext context){
    return Scaffold(
      body: FutureBuilder<LatLng>(
        future: ull,
        builder: ( context , AsyncSnapshot<LatLng> snapshot){
          Widget g;
          if(snapshot.hasData){            
            g = googleMap(_userLocation);            
          }else if(snapshot.hasError){
            g = googleMap(_center);
          }else{
            g = googleMap(_center);
          }

          return g;
        }
      ),
      
        floatingActionButton: Column(mainAxisAlignment: MainAxisAlignment.end, children: <Widget>[
          ElevatedButton(
              onPressed: () {}, 
              
              style: ElevatedButton.styleFrom(
                  primary: ourGreen,
                  shape: const CircleBorder(),
                  padding: const EdgeInsets.all(15),),
                  child: const Icon(Icons.filter_alt_rounded, size: 27, color: ourDark),),
          const SizedBox(height: 9),
          ElevatedButton(
              onPressed: () {centerLocation(); }, 
              style: ElevatedButton.styleFrom(
                  primary: const Color(0xFF1A202C),
                  shape: const CircleBorder(),
                  padding: const EdgeInsets.all(15)),
              child: const Icon(Icons.location_on,
                  size: 27, color: Colors.greenAccent)),
        ]),
    );
  }
}
```
**Logs**
```
D/MapsInitializer(31390): preferredRenderer: null
D/zzca    (31390): preferredRenderer: null
I/zzca    (31390): Making Creator dynamically
I/DynamiteModule(31390): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203115000
I/DynamiteModule(31390): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203115000
V/DynamiteModule(31390): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/e.charging_spo(31390): ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~zVoiiFt7VJAZ8VsgY-Sl4w==/com.example.charging_spot-22TtNgwcYPNnV-LWW6V4Tg==/base.apk*3097498998]{PCL[/system/framework/org.apache.http.legacy.jar*3239720430]})
I/Google Maps Android API(31390): Google Play services client version: 12451000
I/Google Maps Android API(31390): Google Play services package version: 221514044
I/Google Maps Android API(31390): Google Play services maps renderer version(legacy): 203115000
D/MapsInitializer(31390): loadedRenderer: LEGACY
D/zzca    (31390): preferredRenderer: null
I/Google Maps Android API(31390): Google Play services package version: 221514044
I/Google Maps Android API(31390): Google Play services maps renderer version(legacy): 203115000
D/CompatibilityChangeReporter(31390): Compat change id reported: 171228096; UID 10355; state: ENABLED
2
E/FrameEvents(31390): updateAcquireFence: Did not find frame.
W/TextView(31390): onProvideContentCaptureStructure(): calling assumeLayout()
E/GoogleMapController(31390): Cannot enable MyLocation layer as location permissions are not granted
W/Activity(31390): Can request only one set of permissions at a time
E/FrameEvents(31390): updateAcquireFence: Did not find frame.
I/ba      (31390): Successfully registered with Phenotype.
E/FrameEvents(31390): updateAcquireFence: Did not find frame.
E/libprocessgroup(31390): set_timerslack_ns write failed: Operation not permitted
5
E/FrameEvents(31390): updateAcquireFence: Did not find frame.
W/DynamiteModule(31390): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(31390): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:6
I/DynamiteModule(31390): Selected remote version of com.google.android.gms.googlecertificates, version >= 6
W/e.charging_spo(31390): ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~zVoiiFt7VJAZ8VsgY-Sl4w==/com.example.charging_spot-22TtNgwcYPNnV-LWW6V4Tg==/base.apk*3097498998]{PCL[/system/framework/org.apache.http.legacy.jar*3239720430]})
W/SnapshotHandler(31390): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.example.charging_spot, using defaults.
W/SnapshotHandler(31390): java.io.FileNotFoundException: /data/user/0/com.example.charging_spot/files/phenotype/shared/com.google.android.libraries.consentverifier#com.example.charging_spot.pb: open failed: ENOENT (No such file or directory)
W/SnapshotHandler(31390): 	at libcore.io.IoBridge.open(IoBridge.java:575)
W/SnapshotHandler(31390): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/SnapshotHandler(31390): 	at zb.d(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/SnapshotHandler(31390): 	at yw.d(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/SnapshotHandler(31390): 	at zq.b(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):1)
W/SnapshotHandler(31390): 	at zp.a(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):1)
W/SnapshotHandler(31390): 	at yt.b(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):0)
W/SnapshotHandler(31390): 	at wt.a(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):3)
W/SnapshotHandler(31390): 	at xx.a(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):15)
W/SnapshotHandler(31390): 	at avb.d(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):0)
W/SnapshotHandler(31390): 	at fo.c(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):26)
W/SnapshotHandler(31390): 	at fn.a(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):84)
W/SnapshotHandler(31390): 	at fn.b(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):0)
W/SnapshotHandler(31390): 	at in.c(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):1)
W/SnapshotHandler(31390): 	at ie.e(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):1)
W/SnapshotHandler(31390): 	at jf.t(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/SnapshotHandler(31390): 	at jf.u(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):1)
W/SnapshotHandler(31390): 	at jf.e(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/SnapshotHandler(31390): 	at jj.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):69)
W/SnapshotHandler(31390): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/SnapshotHandler(31390): 	at android.os.Looper.loopOnce(Looper.java:201)
W/SnapshotHandler(31390): 	at android.os.Looper.loop(Looper.java:288)
W/SnapshotHandler(31390): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/SnapshotHandler(31390): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/SnapshotHandler(31390): 	at libcore.io.Linux.open(Native Method)
W/SnapshotHandler(31390): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W/SnapshotHandler(31390): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
W/SnapshotHandler(31390): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
W/SnapshotHandler(31390): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
W/SnapshotHandler(31390): 	at libcore.io.IoBridge.open(IoBridge.java:561)
W/SnapshotHandler(31390): 	... 22 more
W/MobStoreFlagStore(31390): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.example.charging_spot, may result in stale flags.
W/MobStoreFlagStore(31390): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.charging_spot, sha256=[aea8950866142e67d5e4ba221aba190b7dab4e72079674e2350feacbd318c1a3], atk=false, ver=221514044.true (go/gsrlt)
W/MobStoreFlagStore(31390): 	at agw.s(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):3)
W/MobStoreFlagStore(31390): 	at agw.get(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/MobStoreFlagStore(31390): 	at aig.g(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/MobStoreFlagStore(31390): 	at wy.c(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):1)
W/MobStoreFlagStore(31390): 	at xa.run(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):0)
W/MobStoreFlagStore(31390): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/MobStoreFlagStore(31390): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/MobStoreFlagStore(31390): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/MobStoreFlagStore(31390): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/MobStoreFlagStore(31390): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/MobStoreFlagStore(31390): 	at java.lang.Thread.run(Thread.java:920)
W/MobStoreFlagStore(31390): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.charging_spot, sha256=[aea8950866142e67d5e4ba221aba190b7dab4e72079674e2350feacbd318c1a3], atk=false, ver=221514044.true (go/gsrlt)
W/MobStoreFlagStore(31390): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
W/MobStoreFlagStore(31390): 	at android.os.Parcel.createException(Parcel.java:2409)
W/MobStoreFlagStore(31390): 	at android.os.Parcel.readException(Parcel.java:2392)
W/MobStoreFlagStore(31390): 	at android.os.Parcel.readException(Parcel.java:2334)
W/MobStoreFlagStore(31390): 	at ea.aZ(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/MobStoreFlagStore(31390): 	at qp.a(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):4)
W/MobStoreFlagStore(31390): 	at ig.e(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/MobStoreFlagStore(31390): 	at jf.t(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/MobStoreFlagStore(31390): 	at jf.u(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):3)
W/MobStoreFlagStore(31390): 	at jf.e(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):2)
W/MobStoreFlagStore(31390): 	at jj.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@221514097@22.15.14 (190400-0):69)
W/MobStoreFlagStore(31390): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore(31390): 	at android.os.Looper.loopOnce(Looper.java:201)
W/MobStoreFlagStore(31390): 	at android.os.Looper.loop(Looper.java:288)
W/MobStoreFlagStore(31390): 	at android.os.HandlerThread.run(HandlerThread.java:67)
4
E/FrameEvents(31390): updateAcquireFence: Did not find frame.
....
```

**Comment by Lyokone** [comment]
Already fixed (or was reported against an old version with different internals). Current `hasPermission()` implementation is a pure check: `MethodCallHandlerImpl.onHasPermission` calls `location.permissionStatusCode()`, which only calls `ActivityCompat.checkSelfPermission` for fine/coarse location -- it never calls `ActivityCompat.requestPermissions` or shows any system dialog. Only `requestPermission()` (a separate method) triggers the actual permission prompt. If you're still seeing `hasPermission()` show a dialog on a current release, please reopen with your plugin version and a reproduction.
