### ISSUE TITLE
Getting A Crash On Android 11 

### ISSUE THREAD

**Issue by liamsammut97** [Lyokone/flutterlocation#728]
Getting a crash on android 11, i cant seem to replicate it but crashlytics log displaying this.

Caused by java.lang.IllegalStateException
Reply already submitted
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:35)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:14)
com.lyokone.location.FlutterLocation.onActivityResult (FlutterLocation.java:48)

**Comment by urbanjagodic** [comment]
There is a problem with the package, specifically in the FlutterLocation.java class, where
MethodChannel Result object  is submitted back through dart binary messenger on several occurrences resulting in    `Reply already submitted` error.

## Use case execution scenario: 

> If user has location disabled, when application calls requestService method, and is presented with enable location service dialog, he then chooses to cancel the location service, the app crashes.


#### Code resulting in application crash: 

In my case that happens, when i invoke requestPermission method before the getLocation method.

```dart

if (await location.requestPermission() == PermissionStatus.granted) {
      // get device location.
    return await location.getLocation()
  }
```

Requesting permissions should be invoked only once in the application lifetime, somwhere on the application startup or user login.

requestPermission() method should not be superseeded by the getLocation method, which results in the error described above, where result object is already submitted back to platform channel.

## Workaround

Use hasPermission method before requesting device location, to avoid duplicate result object replies.

```dart
if (await location.hasPermission() == PermissionStatus.granted) {
     // get device location.
    return await location.getLocation()
 }
```

Check the workflow of requesting device location in your app, and fix the similarities i have pointed out.

**Comment by raphael-bmec-co** [comment]
I am seeing a similar issue but with a different trigger. Location permission has already been requested and granted in the below.

## Description
When the Android system setting "Improve Location Accuracy" is disabled, calling `changeSettings()` with `LocationAccuracy.high` triggers a system dialog asking the user to enable it. If the user clicks "No" to deny the request, the app crashes with `IllegalStateException: Reply already submitted`.

Additionally, the method returns `true` to Dart even though the user denied the request, making it impossible to detect the denial and handle it gracefully.

## Environment
- **Package version**: `location: ^8.0.0`
- **Platform**: Android
- **Device/Emulator**: [Tested on physical device]

## Steps to Reproduce
1. On an Android device, disable "Improve Location Accuracy" in system settings (Settings → Location → Location Services → Improve Location Accuracy → OFF)
2. Call `changeSettings()` with `LocationAccuracy.high`:
   ```dart
   bool success = await location.changeSettings(
     accuracy: LocationAccuracy.high,
     interval: 1000,
   );
   ```
3. Android shows a dialog: "For a better location experience, turn on device location, which uses Google's location service"
4. Click "No Thanks" to deny the request
5. App crashes

## Expected Behavior
- No crash should occur
- `changeSettings()` should return `false` when the user denies the accuracy request
- App should be able to detect the denial and handle it gracefully (e.g., fall back to lower accuracy or show a warning)

## Actual Behavior
- App crashes with `IllegalStateException: Reply already submitted`
- Before crashing, `changeSettings()` returns `true` to Dart, even though the request was denied
- The crash occurs in the plugin's `onActivityResult` method, which attempts to submit a reply twice

## Stack Trace
```
E/AndroidRuntime(11421): FATAL EXCEPTION: main
E/AndroidRuntime(11421): Process: co.bmec.rei004.dev, PID: 11421
E/AndroidRuntime(11421): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent {  }} to activity {co.bmec.rei004.dev/co.bmec.rei004.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11421):     at android.app.ActivityThread.deliverResults(ActivityThread.java:5621)
E/AndroidRuntime(11421):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5660)
E/AndroidRuntime(11421):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime(11421):     ...
E/AndroidRuntime(11421): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11421):     at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime(11421):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:277)
E/AndroidRuntime(11421):     at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:183)
E/AndroidRuntime(11421):     at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:774)
E/AndroidRuntime(11421):     ...
```

## Root Cause
The plugin's `FlutterLocation.onActivityResult()` method at line 183 attempts to send a reply to the Flutter method channel after a reply has already been sent. This happens when `resultCode=0` (user denied).

## Workaround
We've implemented a workaround by catching the exception in `MainActivity.onActivityResult()`:

```kotlin
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    try {
        super.onActivityResult(requestCode, resultCode, data)
    } catch (e: IllegalStateException) {
        if (e.message?.contains("Reply already submitted") == true &&
            e.stackTrace.any { it.className.contains("com.lyokone.location.FlutterLocation") }
        ) {
            Log.e("MainActivity", "Location plugin exception: ${e.message}")
        } else {
            throw e
        }
    }
}
```

However, this only prevents the crash - it doesn't fix the incorrect return value issue.

## Suggested Fix
In `FlutterLocation.java` (or `.kt`), the `onActivityResult` method should:
1. Check if a reply has already been sent before attempting to send another
2. Return `false` to Dart when the user denies the accuracy request (resultCode != RESULT_OK)
3. Ensure only one reply is sent per method call

**Comment by raphael-bmec-co** [comment]
Note this fix is not obscurification safe so it may be best to remove the guard: `it.className.contains("com.lyokone.location.FlutterLocation")`

**Comment by Lyokone** [comment]
Very likely fixed by a merged PR this session (#1076). The old Java `onActivityResult` (referenced in this crash) had a bug where the settings-resolution dialog's outcome checked/completed the wrong pending-result field, which could leave things in an inconsistent state. Current Kotlin `onActivityResult` clears every pending result (`getLocationResults`, `events`, `requestServiceResult`) immediately upon resolving it in every branch, and I traced all three `requestCode` cases to confirm there's no remaining path where a `Result` could be completed twice (which is what `IllegalStateException: Reply already submitted` means). Please reopen with a fresh stack trace if this still reproduces on the current release.

**Comment by FreedomSwDev** [comment]
Update: I was using version 8.x.x. I updated to 10.0.2 and the issue disappeared, thank you.


I'm having this issue, not when I run my app in debug mode but when I upload it in Google play console, Play console register a crash and it doesn't let me publish the app. The strange thing is that the app is already published and I haven't changed the code around location. And I have other apps very very similar that use location and they pass the google play console test.


```
08-06 04:41:26.143 10521 10521 E AndroidRuntime: FATAL EXCEPTION: main
08-06 04:41:26.143 10521 10521 E AndroidRuntime: Process: ..........., PID: 10521
08-06 04:41:26.143 10521 10521 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=Intent { xflg=0x4 }} to activity {..................MainActivity}: java.lang.IllegalStateException: Reply already submitted
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6184)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6223)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:78)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2823)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:248)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:338)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9067)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Reply already submitted
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:425)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:277)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at com.lyokone.location.FlutterLocation.onActivityResult(FlutterLocation.java:183)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:795)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:443)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:1006)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:926)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.Activity.onActivityResult(Activity.java:7626)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.Activity.internalDispatchActivityResult(Activity.java:9546)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:9523)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6173)
08-06 04:41:26.143 10521 10521 E AndroidRuntime: 	... 14 more

```
