### ISSUE TITLE
Error in google play console How to solve?

### ISSUE THREAD

**Issue by lbarria77** [Lyokone/flutterlocation#747]
at com.lyokone.location.b$a.onServiceConnected(Unknown Source:30)

FATAL EXCEPTION: main
Process: com.wahoo_express_delivery, PID: 7636
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/activity/ComponentActivity;
	at k0.d.k(Unknown Source:0)
	at com.google.android.gms.common.api.internal.c.x(Unknown Source:21)
	at l0.e.<init>(Unknown Source:78)
	at l0.e.<init>(Unknown Source:6)
	at l0.e.<init>(Unknown Source:19)
	at d1.b.<init>(Unknown Source:8)
	at d1.f.a(Unknown Source:2)
	at com.lyokone.location.a.u(Unknown Source:4)
	at com.lyokone.location.FlutterLocationService.k(Unknown Source:7)
	at com.lyokone.location.b.e(Unknown Source:8)
	at com.lyokone.location.b.a(Unknown Source:0)
	at com.lyokone.location.b$a.onServiceConnected(Unknown Source:30)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.ClassNotFoundException: androidx.activity.ComponentActivity
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 21 more
Caused by: java.lang.IllegalAccessError: Class androidx.core.app.d extended by class androidx.activity.ComponentActivity is inaccessible (declaration of 'androidx.activity.ComponentActivity' appears in /data/app/com.wahoo_express_delivery-eTIZjtXDIQcu9_GoBXFX4w==/base.apk)
	... 21 more

**Comment by bartekpacia** [comment]
This is very likely fixed on the latest v5 versions.
