### ISSUE TITLE
fix: The app crashes once I grant permission to access location

### ISSUE THREAD

**Issue by Shiba-Kar** [Lyokone/flutterlocation#768]
**Description**
The app crashes once I grant permission to access location.

**Expected behavior**
The app crashes once I grant permission to access location in an emulator but not with a real device.

**Steps To Reproduce**

1. Grant access to location
2. See error

**Tested on:**

- Android, API Level 12 , emulator
- Latest 5.0.0-dev.8

**Other plugins:**

- Geocoding : 2.0.5

**Additional logs**

```shell
D/Location(10668): onPermissionGranted
D/EGL_emulation(10668): app_time_stats: avg=31.62ms min=4.31ms max=797.90ms count=47
D/Location(10668): onActivityResult
D/Location(10668): onProcessTypeChanged
D/Location(10668): GETTING_LOCATION_FROM_GOOGLE_PLAY_SERVICES
D/EGL_emulation(10668): app_time_stats: avg=1402.65ms min=38.25ms max=3712.06ms count=3
D/LOCATION(10668): 37.4214938 -122.083922
D/AndroidRuntime(10668): Shutting down VM
E/AndroidRuntime(10668): FATAL EXCEPTION: main
E/AndroidRuntime(10668): Process: com.swazei.totempole2, PID: 10668
E/AndroidRuntime(10668): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
E/AndroidRuntime(10668): 	at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
E/AndroidRuntime(10668): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
E/AndroidRuntime(10668): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationResult(GooglePlayServicesLocationProvider.java:141)
E/AndroidRuntime(10668): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource.onLocationResult(GooglePlayServicesLocationSource.java:99)
E/AndroidRuntime(10668): 	at com.google.android.gms.internal.location.zzap.notifyListener(com.google.android.gms:play-services-location@@18.0.0:2)
E/AndroidRuntime(10668): 	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.0.1:2)
E/AndroidRuntime(10668): 	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
E/AndroidRuntime(10668): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10668): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10668): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10668): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10668): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(10668): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10668): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10668): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (10668): Sending signal. PID: 10668 SIG: 9
Lost connection to device.
```

**Comment by PlugFox** [comment]
The same for me

**Comment by PlugFox** [comment]
```dart
D/Location( 6123): onPermissionGranted
D/LOCATION( 6123): 37.4220936 -122.083922
D/AndroidRuntime( 6123): Shutting down VM
E/AndroidRuntime( 6123): FATAL EXCEPTION: main
E/AndroidRuntime( 6123): Process: uk.co.cityplumbing.express_app.uat, PID: 6123
E/AndroidRuntime( 6123): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
E/AndroidRuntime( 6123): 	at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
E/AndroidRuntime( 6123): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
E/AndroidRuntime( 6123): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLastKnowLocationTaskReceived(GooglePlayServicesLocationProvider.java:211)
E/AndroidRuntime( 6123): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource$3.onComplete(GooglePlayServicesLocationSource.java:92)
E/AndroidRuntime( 6123): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime( 6123): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6123): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6123): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6123): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6123): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime( 6123): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6123): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6123): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process ( 6123): Sending signal. PID: 6123 SIG: 9
Lost connection to device.
```

**Comment by SKTDeveloper99** [comment]
I am quite confused actually. Why is it flutterlocation crashes while geolocator doesn't

**Comment by bartekpacia** [comment]
Hi, please use the "normal", [latest v5 version](https://pub.dev/packages/location), not the `v5.0.0-dev*` versions.
