### ISSUE TITLE
fix: Location plugin is incompatible with latest play-services-location

### ISSUE THREAD

**Issue by Ghoelian** [Lyokone/flutterlocation#788]
**Description**
The plugin is incompatible with the latest com.google.android.gms:play-services-location, 21.0.1.

**Expected behavior**
The app runs.

**Steps To Reproduce**
1. Install the plugin
2. Add / change ``implementation "com.google.android.gms:play-services-location:21.0.1"`` in your app's build.gradle dependencies
3. Try to launch app

**Tested on:**

- Android, API Level 33, emulator
- Android, API Level 28 (Android 9.0), real device

**Other plugins:**

- None that I think could interfere

**Additional logs**

```shell
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~Btvdfhqi95-Fg_senEQppw==/nl.paytree.paytree_pos-HAQsmK9UNgM5XqakyhO3nA==/base.apk)
E/AndroidRuntime(21578): 	at com.lyokone.location.FlutterLocation.createLocationCallback(FlutterLocation.java:219)
E/AndroidRuntime(21578): 	at com.lyokone.location.FlutterLocation.changeSettings(FlutterLocation.java:197)
E/AndroidRuntime(21578): 	at com.lyokone.location.MethodCallHandlerImpl.onChangeSettings(MethodCallHandlerImpl.java:106)
E/AndroidRuntime(21578): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/AndroidRuntime(21578): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(21578): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(21578): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(21578): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(21578): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(21578): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21578): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(21578): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(21578): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(21578): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21578): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(21578): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by liyao20190808** [comment]
Same issue.

**Comment by praveenstratagile** [comment]
found any solution?

**Comment by LaxmikanthMadhyastha** [comment]
This happening to me also, the app is crashing on startup.

**Comment by nmbmejia** [comment]
Damn same here. Any alternatives?

**Comment by hookipatm2** [comment]
same here - am stuck - I cannot even seem to be able to roll back anything ... any work around?

**Comment by adiiisanjayaa** [comment]
any update?

**Comment by nmbmejia** [comment]
Hi all. Just reporting back I haven’t found a fix but am now using Geolocator. I just need it to fetch user location.

**Comment by Lyokone** [comment]
9.0.0 depends on play-services-location 21.3.0 and the Android plugin was rewritten, so the incompatibility with the newer play-services is resolved.

https://pub.dev/packages/location/versions/9.0.0

Closing.
