### ISSUE TITLE
Bug: askForGPS: false is ignored

### ISSUE THREAD

**Issue by MichaelTamm** [Lyokone/flutterlocation#797]
Hi,

when trying out the 5.0.0-dev.8 version of the location package, I used the following Dart code:
```
    final locationData = await getLocation(
      settings: LocationSettings(
        askForGPS: false,
        askForPermission: false,
    ));
```

and got the following exception:
```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:856)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:819)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:707)
	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
	at android.app.Dialog.show(Dialog.java:342)
	at com.lyokone.location.location.providers.locationprovider.DefaultLocationProvider.askForEnableGPS(DefaultLocationProvider.java:116)
	at com.lyokone.location.location.providers.locationprovider.DefaultLocationProvider.get(DefaultLocationProvider.java:103)
	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.continueWithDefaultProviders(DispatcherLocationProvider.java:231)
	at com.lyokone.location.location.providers.locationprovider.DispatcherLocationProvider.runScheduledTask(DispatcherLocationProvider.java:88)
	at com.lyokone.location.location.helper.continuoustask.ContinuousTask.run(ContinuousTask.java:49)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
indicating that `DefaultLocationProvider.askForEnableGPS` was called, although I explicitly specified `askForGPS: false`.

Expected behaviour: I think `DefaultLocationProvider.askForEnableGPS` should not be called in this case.

**Comment by fairuzmn** [comment]
i got same bug, 
you can check gps status before call `getLocation` or `onLocationChanged`

the bug exist after i denied twice location permission request from this package

here is my code, i used [app_setting](https://pub.dev/packages/app_settings) for request enable gps by directing user to their gps setting 

```
Future<bool> ensureGpsStatus() async {
    bool gpsStatus = await isGPSEnabled();
    if (!gpsStatus) await AppSettings.openLocationSettings();
   
    return gpsStatus;
}
```

**Comment by AntoineBrah** [comment]
I'm facing same, happens when I deny either location permission or gps

**Comment by bartekpacia** [comment]
Please use the [latest v5 version](https://pub.dev/packages/location), not the `dev` one.

See also: #870.
