### ISSUE TITLE
fix:  java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.a, but class was expected (declaration of 'com.google.android.gms.location.a' appears in base.apk

### ISSUE THREAD

**Issue by lalit3102** [Lyokone/flutterlocation#810]
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.a, but class was expected (declaration of 'com.google.android.gms.location.a' appears in base.apk)
       at com.lyokone.location.FlutterLocation.setActivity(FlutterLocation.java:32)
       at com.lyokone.location.FlutterLocationService.setActivity(FlutterLocationService.java:6)
       at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:50)
       at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java)
       at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:33)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:58)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at android.app.Activity.performDestroy(Activity.java:8851)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6126)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by iBehruz** [comment]
same here

**Comment by hiimtrung** [comment]
same

**Comment by Jacqueline94-Koo** [comment]
follow

**Comment by adamramadhn** [comment]
same

**Comment by mathiasgodwin** [comment]
same here

**Comment by saulrmzlpz** [comment]
I change dependency to https://pub.dev/packages/geolocator
Problem solved.

**Comment by akadatsky** [comment]
It happens cause Last October, Android [made a breaking change](https://developers.google.com/android/guides/releases#october_13_2022) to play-services:location in v21.

But this plugin still depends on older version:
https://github.com/Lyokone/flutterlocation/blob/master/packages/location_android/android/build.gradle

The solution, as mention above is to replace this plugin with https://pub.dev/packages/geolocator

**Comment by Parvez6084** [comment]
i got it solved after adding the followings lines to allprojects:

```
maven {
           url 'https://google.bintray.com/exoplayer/'
       }
       //** add this line
       configurations.all {
           resolutionStrategy {
               force "com.google.android.gms:play-services-location:21.0.1"
           }
```
**android\build.gradle:**
```

buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }


    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://google.bintray.com/exoplayer/'
        }
        //** add this line
        configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-location:21.0.1"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

**Comment by bartekpacia** [comment]
This is fixed in the latest v5 versions. Please use them.
