### ISSUE TITLE
Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference

### ISSUE THREAD

**Issue by BrendanBasson4** [Lyokone/flutterlocation#814]
**Description**
So I'm receiving a push notification that should then trigger the package to get the location. It works when the app is in the foreground but throws 

> Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference

 when the app is in the background. Note: background mode is enabled.

**Expected Behavior** 
I want the location even when the app is in the background.

**Steps To Reproduce**

1. Install Firebase messaging.
2. Set the app in the background with location service in background mode.
3. receive the background push notification.
4. trigger getLocation function
5. See Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference

**Tested on:**

- Android, API Level 29, simulator

**Other plugins:**

 firebase_messaging: ^14.2.2

**Additional logs**

```
E/MethodChannel#lyokone/location( 6178): Failed to handle method call
E/MethodChannel#lyokone/location( 6178): java.lang.NullPointerException: Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference
E/MethodChannel#lyokone/location( 6178): 	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:117)
E/MethodChannel#lyokone/location( 6178): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
E/MethodChannel#lyokone/location( 6178): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#lyokone/location( 6178): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#lyokone/location( 6178): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#lyokone/location( 6178): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#lyokone/location( 6178): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#lyokone/location( 6178): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#lyokone/location( 6178): 	at android.os.Looper.loop(Looper.java:214)
E/MethodChannel#lyokone/location( 6178): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#lyokone/location( 6178): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#lyokone/location( 6178): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#lyokone/location( 6178): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by LassazVegaz** [comment]
I am getting the same

**Comment by naiadelali** [comment]
same here

**Comment by davidalonsobadia** [comment]
same here

**Comment by fredyrx** [comment]
same here

**Comment by darul9061** [comment]
same here

**Comment by RajaShanmugamJM** [comment]
Any work arounds or solutions here?

**Comment by spiderion** [comment]
Same here. But I happens when I try to get the user location via push notification

**Comment by sanaullah-dev** [comment]
**same here:**
PlatformException(error, Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference in method 'void com.lyokone.location.MethodCallHandlerImpl.onGetLocation(io.flutter.plugin.common.MethodChannel$Result)', null, java.lang.NullPointerException: Attempt to write to field 'io.flutter.plugin.common.MethodChannel$Result com.lyokone.location.FlutterLocation.getLocationResult' on a null object reference in method 'void com.lyokone.location.MethodCallHandlerImpl.onGetLocation(io.flutter.plugin.common.MethodChannel$Result)'
      	at com.lyokone.location.MethodCallHandlerImpl.onGetLocation(MethodCallHandlerImpl.java:117)
      	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:43)
      	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
      	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
      	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
      	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
      	at android.os.Handler.handleCallback(Handler.java:942)
      	at android.os.Handler.dispatchMessage(Handler.java:99)
      	at android.os.Looper.loopOnce(Looper.java:240)
      	at android.os.Looper.loop(Looper.java:351)
      	at android.app.ActivityThread.main(ActivityThread.java:8377)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
      )

**Comment by sanaullah-dev** [comment]
how we can get background **location when notification** method trigger.

**Comment by rakshitha-dilshan** [comment]
Anyone found a solution?

**Comment by jsuarez-73** [comment]
I was having the same issue with the WorkManager plugin: https://pub.dev/packages/workmanager
I realized the problem with location occurs because background tasks are executed in Isolates, meaning the main thread and the background isolate don't share the same memory space. So, when you try to get the location, the plugin returns null because there is no instance of the location plugin in that memory space. The solution could be to create a communication channel between the two. Maybe FirebaseMessaging also executes Isolate.

Cheers!

**Comment by Lyokone** [comment]
Already fixed by the Kotlin rewrite (published in `location` 9.0.0). `MethodCallHandlerImpl.kt` now null-checks the attached `FlutterLocation` up front (lines 31-35) and returns a `NO_ACTIVITY` `PlatformException` instead of crashing:

```kotlin
val location = this.location
if (location == null) {
    result.error("NO_ACTIVITY", "Location is not attached to an activity.", null)
    return
}
```

The old Java `MethodCallHandlerImpl.onMethodCall` (what this crash was reported against) had no such guard, so `getLocation()` called from a headless/no-Activity context (e.g. a Firebase Messaging background handler) wrote directly to a null `FlutterLocation`, causing the reported NPE. If this still reproduces on the current release, please reopen with a fresh stack trace.
