### ISSUE TITLE
Crashes the app with Fatal Exception

### ISSUE THREAD

**Issue by arnabonetraker** [Lyokone/flutterlocation#841]
Hi, The app is crashing on initialisation. As soon as I give permission, the app crashes.
I am using `location:^500-dev8`.
Here are the logs:
```
D/AndroidRuntime(16976): Shutting down VM
E/AndroidRuntime(16976): FATAL EXCEPTION: main
E/AndroidRuntime(16976): Process: com.example.demo_background_location, PID: 16976
E/AndroidRuntime(16976): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
E/AndroidRuntime(16976): 	at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
E/AndroidRuntime(16976): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
E/AndroidRuntime(16976): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLastKnowLocationTaskReceived(GooglePlayServicesLocationProvider.java:211)
E/AndroidRuntime(16976): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource$3.onComplete(GooglePlayServicesLocationSource.java:92)
E/AndroidRuntime(16976): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(16976): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(16976): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16976): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(16976): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(16976): 	at android.app.ActivityThread.main(ActivityThread.java:8380)
E/AndroidRuntime(16976): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16976): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(16976): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```
I am running latest flutter 3.10.0, But I also tried with flutter 3.7, same results.
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by UffizioHimanshu** [comment]
Same issue triggering to me...any help would be appreciated.

**Comment by Jackson-Antunes-Sampaio** [comment]
Same issue triggering to me

**Comment by dannycortesv** [comment]
Same issue...

**Comment by nadiahylary** [comment]
Same issue and I'm also using ^5.0.0-dev.8.

**Comment by arnabonetraker** [comment]
> Same issue and I'm also using ^5.0.0-dev.8. At first I used ^4.4.0 but the build kept failing no matter all the solutions I attempted.

For now you could downgrade your gradle version to `gradle:7.2.0` also your kotlin version to `1.7.10`.
For me if I downgrade to these build success with `^4.4.0`, for now you could try this.

**Comment by perseoGI** [comment]
Same issue here!

**Comment by RoshanSahani108** [comment]
same issue...

**Comment by Shabeebcp** [comment]
Add in Your Gradle File


```
rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
        configurations.all{
            resolutionStrategy{
             force "com.google.android.gms:play-services-location:21.0.1"
         }
 }
    }
}
```

**Comment by bartekpacia** [comment]
Hi! Please use the "normal", [latest v5 version](https://pub.dev/packages/location). It doesn't include changes from the old `v5.0.0-dev*` versions. See also issue #870.
