### ISSUE TITLE
On Android in release mode, getLocation fails intermittently with PlatformException (null object reference)

### ISSUE THREAD

**Issue by dixiak** [Lyokone/flutterlocation#885]
Works fine in Debug mode and about 50% of the time in Release.
The rest of the time it just throws an exception.

Tested on:
 - Android, API Level 33 real device 
 - Android, API Level 30 real device 
 - Emulator, API Level 33 - Does not repro!

Other plugins:
  grpc: ^3.1.0
  connectivity_plus: ^4.0.2
  location: ^5.0.3

D/FlutterLocationService(11083): Creating service.
D/FlutterLocationService(11083): Binding to location service.
E/flutter (11083): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to write to field 't0.j$d com.lyokone.location.a.p' on a null object reference, null, java.lang.NullPointerException: Attempt to write to field 't0.j$d com.lyokone.location.a.p' on a null object reference
E/flutter (11083): 	at com.lyokone.location.c.f(Unknown Source:2)
E/flutter (11083): 	at com.lyokone.location.c.a(Unknown Source:149)
E/flutter (11083): 	at t0.j$a.a(Unknown Source:17)
E/flutter (11083): 	at h0.c.j(Unknown Source:18)
E/flutter (11083): 	at h0.c.k(Unknown Source:40)
E/flutter (11083): 	at h0.c.g(Unknown Source:0)
E/flutter (11083): 	at h0.b.run(Unknown Source:12)
E/flutter (11083): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (11083): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (11083): 	at android.os.Looper.loop(Looper.java:246)
E/flutter (11083): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
E/flutter (11083): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11083): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/flutter (11083): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (11083): )
E/flutter (11083): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
E/flutter (11083): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
E/flutter (11083): <asynchronous suspension>
E/flutter (11083): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:510)
E/flutter (11083): <asynchronous suspension>
E/flutter (11083): #3      MethodChannelLocation.getLocation (package:location_platform_interface/src/method_channel_location.dart:83)
E/flutter (11083): <asynchronous suspension>

**Comment by yogeshelevn** [comment]
we are still getting this issue in release mode in latest version of location library ^8.0.1

**Comment by baudine-dreamtec** [comment]
We are also getting this after updating to the latest library 8.0.1. Our full log from crashlytics:
PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference at com.lyokone.location.FlutterLocation.checkPermissions(FlutterLocation.java:331) at com.lyokone.location.MethodCallHandlerImpl.onHasPermission(MethodCallHandlerImpl.java:131) at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:46) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267) at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292) at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java

```
permissionLocation() async { //log points to this line
    late bool serviceEnabled;
    late PermissionStatus permissionGranted;

    Location locationService = Location();
    bool success = true;
    serviceEnabled = await locationService.serviceEnabled();
    if (!serviceEnabled) {
      serviceEnabled = await locationService.requestService();
      if (!serviceEnabled) {
        success = false;
        //if (mounted) showAccessLocationDenyDialog(context); iOS does not want the app to be blocked
      }
    }

    permissionGranted = await locationService.hasPermission();
    if (permissionGranted == PermissionStatus.denied) {
      permissionGranted = await locationService.requestPermission();
      if (permissionGranted != PermissionStatus.granted) {
        success = false;
        //if (mounted) showAccessLocationDenyDialog(context); iOS does not want the app to be blocked
      }
    }

    var myNotification = await ph.Permission.notification.request();
    if (myNotification.isDenied|| myNotification.isPermanentlyDenied) {
      if (mounted) {
        //showDenyPermissionOpenSettings(context,StringConstants.getNotificationPermissionRequiredTitle(userType),
        //    StringConstants.getNotificationPermissionRequiredBody(userType)); iOS does not want the app to be blocked
      }
    } 

    if (success) {
      permissionAlways();
    }
  }
```

**Comment by Lyokone** [comment]
This is on `location: ^5.0.3` (pre-Kotlin-rewrite) and the truncated "null object reference" error doesn't show a full stack trace in the report. Release-mode-only crashes on old Java-based Android plugins are often an R8/ProGuard keep-rule issue. Could you confirm whether this still reproduces on the current release, and if so share the full stack trace from `adb logcat` (not just the summary line) so the actual null reference can be pinned down?

**Comment by Lyokone** [comment]
Traced this properly using the full stack trace from the second comment (thank you for including it):

```
NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(...)' on a null object reference
  at com.lyokone.location.FlutterLocation.checkPermissions(FlutterLocation.java:331)
  at com.lyokone.location.MethodCallHandlerImpl.onHasPermission(MethodCallHandlerImpl.java:131)
```

This is a real bug, but specific to the old Java implementation: `checkPermissions()` called `result.error(...)` directly on the nullable `result` field with no null check — Java has no compile-time null safety, so whenever `result` was actually null at that point (which `onHasPermission`'s code path could hit), this threw an unguarded NPE. That's consistent with it being release-mode-only and intermittent (R8 can also reorder/inline code in ways that change exactly when this race is hit, but the underlying gap is the missing null check, present in debug too).

Both reports are on `location: ^5.0.3`/`^8.0.1` — both predate the Kotlin rewrite that shipped as `9.0.0`. I audited the current Kotlin implementation specifically for this: `onHasPermission` no longer calls `checkPermissions()` at all (it calls `permissionStatusCode()`, which only reads permission state, no `result` field involved), and every remaining access to the nullable `result` field elsewhere in `FlutterLocation.kt` uses Kotlin's null-safe `?.` operator (`result?.error(...)`, `result?.success(...)`) rather than the unguarded Java call that crashed here. This class of NPE structurally can't happen anymore.

Closing as fixed by the Kotlin rewrite. If you can still reproduce a crash with this same "on a null object reference" signature on the current `location` version, please reopen with the full stack trace (like the second report here) so it can be pinned to the actual current line.
