### ISSUE TITLE
Could not get current location

### ISSUE THREAD

**Issue by rajesh170** [Lyokone/flutterlocation#904]
**Describe the bug**
A clear and concise description of what the bug is. Have you tried running `flutter clean` first ?

**Expected behavior**

**Tested on:**
 - Android, API Level XX [e.g. 28], simulator or real device
 - iOS, Version XX [e.g. 10], simulator or real device

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**

``` shell
some logs
```

**Comment by frg-x** [comment]
I can confirm the problem. Pixel 5 (emulator) API 28. **location.onLocationChanged.listen** doesn't get user location
Here is my error log:
`E/AndroidRuntime(19028): FATAL EXCEPTION: main
E/AndroidRuntime(19028): Process: com.google.android.gms.ui, PID: 19028
E/AndroidRuntime(19028): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0808d3
E/AndroidRuntime(19028): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
E/AndroidRuntime(19028): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
E/AndroidRuntime(19028): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(19028): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(19028): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(19028): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(19028): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19028): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(19028): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(19028): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19028): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(19028): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(19028): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0808d3
E/AndroidRuntime(19028): 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
E/AndroidRuntime(19028): 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
E/AndroidRuntime(19028): 	at android.content.res.Resources.getDrawable(Resources.java:827)
E/AndroidRuntime(19028): 	at android.content.res.Resources.getDrawable(Resources.java:802)
E/AndroidRuntime(19028): 	at bwml.run(:com.google.android.gms@214515028@21.45.15 (100400-411636772):9)
E/AndroidRuntime(19028): 	at android.app.Activity.runOnUiThread(Activity.java:6282)
E/AndroidRuntime(19028): 	at euv.platform_runOnUiThread(:com.google.android.gms@214515028@21.45.15 (100400-411636772):0)
E/AndroidRuntime(19028): 	at euu.runOnUiThread(:com.google.android.gms@214515028@21.45.15 (100400-411636772):0)
E/AndroidRuntime(19028): 	at com.google.android.chimera.android.Activity.runOnUiThread(:com.google.android.gms@214515028@21.45.15 (100400-411636772):0)
E/AndroidRuntime(19028): 	at com.google.android.location.settings.LocationSettingsCheckerChimeraActivity.onCreate(:com.google.android.gms@214515028@21.45.15 (100400-411636772):41)
E/AndroidRuntime(19028): 	at euu.public_onCreate(:com.google.android.gms@214515028@21.45.15 (100400-411636772):1)
E/AndroidRuntime(19028): 	at vel.onCreate(:com.google.android.gms@214515028@21.45.15 (100400-411636772):2)
E/AndroidRuntime(19028): 	at android.app.Activity.performCreate(Activity.java:7136)
E/AndroidRuntime(19028): 	at android.app.Activity.performCreate(Activity.java:7127)
E/AndroidRuntime(19028): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime(19028): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
E/AndroidRuntime(19028): 	... 11 more`

**Comment by jennifer-uitoux** [comment]
any updates on this, im facing the same issue

**Comment by Lyokone** [comment]
Closing due to no information to act on — the issue template was left unfilled (no description, device/version info, or logs). Please reopen with specifics (plugin version, platform/OS version, a reproduction, and any error output) and I'm happy to take another look.
