### ISSUE TITLE
location 7.0.0 make errors at compilation time

### ISSUE THREAD

**Issue by SETSinsperion** [Lyokone/flutterlocation#965]
Hi, good day. When I installed the most recent version of location: ^7.0.0, afterwards the Android emulator launched the app, but the terminal told us the next, I don't know if this behavior is correct:

``` shell
Launching lib\main.dart on sdk **gphone64 x86 64** in debug mode...
e: **Daemon compilation failed: null**
java.lang.Exception

**Caused by: java.lang.AssertionError: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\jvm\kotlin: class-fq-name-to-source.tab, source-to-classes.tab, internal-name-to-source.tab**

Caused by: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\jvm\kotlin: class-fq-name-to-source.tab, source-to-classes.tab, internal-name-to-source.tab

	**Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.**
		
	**Suppressed: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\inputs: source-to-output.tab**

**Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.**

√ Built build\app\outputs\flutter-apk\app-debug.apk
D/FlutterLocationService(12029): Creating service.
D/FlutterLocationService(12029): Binding to location service.
D/LocationPlugin(12029): Service connected: ComponentInfo{com.example.fav_places/com.lyokone.location.FlutterLocationService}
Connecting to VM Service at ws://127.0.0.1:55146/qYAZP4hBEqU=/ws
D/ProfileInstaller(12029): Installing profile for com.example.fav_places
```

**I also increase the Kotlin plugin version in settings.gradle** hoping it could resolve the issue, and execute endless times commands of **flutter clean, upgrade, and pub get**, but like you see I hadn't gotten rid of that error, am I doing something wrong?

**Tested on:**
 - Android, API Level 34, Android Emulator.
 - Windows 11 version 22H2, OS Build 22621.3810
 - IDE: Visual Studio Code 1.90.2
 - Flutter doctor output:
 ```
 [√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22621.3810], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Users\setsi\AppData\Local\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\setsi\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\setsi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 14 (API 34) (emulator)

[√] Network resources
    • All expected network resources are available.
 ```

Complete log:
``` shell
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
e: Daemon compilation failed: null
java.lang.Exception
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:69)
	at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:65)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemon(GradleKotlinCompilerWork.kt:240)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemonOrFallbackImpl(GradleKotlinCompilerWork.kt:159)
	at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:111)
	at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction.execute(GradleCompilerRunnerWithWorkers.kt:76)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:212)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:114)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\jvm\kotlin: class-fq-name-to-source.tab, source-to-classes.tab, internal-name-to-source.tab
	at org.jetbrains.kotlin.com.google.common.io.Closer.close(Closer.java:230)
	at org.jetbrains.kotlin.incremental.IncrementalCachesManager.close(IncrementalCachesManager.kt:55)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:56)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:293)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:676)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1661)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	... 3 more
Caused by: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\jvm\kotlin: class-fq-name-to-source.tab, source-to-classes.tab, internal-name-to-source.tab
	at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:93)
	at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.close(BasicMapsOwner.kt:45)
	at org.jetbrains.kotlin.com.google.common.io.Closer.close(Closer.java:218)
	... 24 more
	Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.
		at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
		at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
		at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:24)
		at org.jetbrains.kotlin.incremental.storage.FileDescriptor.save(FileToPathConverter.kt:33)
		at org.jetbrains.kotlin.incremental.storage.FileDescriptor.save(FileToPathConverter.kt:30)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:378)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:360)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:102)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.applyChanges(InMemoryStorage.kt:108)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:136)
		at org.jetbrains.kotlin.incremental.storage.PersistentStorageWrapper.close(PersistentStorage.kt:109)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
		... 26 more
	Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.
		at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
		at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
		at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:24)
		at org.jetbrains.kotlin.incremental.storage.FileDescriptor.getHashCode(FileToPathConverter.kt:50)
		at org.jetbrains.kotlin.incremental.storage.FileDescriptor.getHashCode(FileToPathConverter.kt:30)
		at org.jetbrains.kotlin.com.intellij.util.containers.hash.HashUtil.hash(HashUtil.java:24)
		at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap.remove(LinkedHashMap.java:149)
		at org.jetbrains.kotlin.com.intellij.util.containers.SLRUMap.remove(SLRUMap.java:116)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.flushAppendCache(PersistentMapImpl.java:924)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:386)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:360)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:102)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.applyChanges(InMemoryStorage.kt:108)
		at org.jetbrains.kotlin.incremental.storage.AppendableInMemoryStorage.applyChanges(InMemoryStorage.kt:175)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:136)
		at org.jetbrains.kotlin.incremental.storage.AppendableSetBasicMap.close(BasicMap.kt:157)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
		... 26 more
	Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.
		at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
		at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
		at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:24)
		at org.jetbrains.kotlin.incremental.storage.FileDescriptor.save(FileToPathConverter.kt:33)
		at org.jetbrains.kotlin.incremental.storage.FileDescriptor.save(FileToPathConverter.kt:30)
		at org.jetbrains.kotlin.incremental.storage.AppendableCollectionExternalizer.save(LazyStorage.kt:134)
		at org.jetbrains.kotlin.incremental.storage.AppendableCollectionExternalizer.save(LazyStorage.kt:125)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:378)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:360)
		at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:102)
		at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.applyChanges(InMemoryStorage.kt:108)
		at org.jetbrains.kotlin.incremental.storage.AppendableInMemoryStorage.applyChanges(InMemoryStorage.kt:175)
		at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:136)
		at org.jetbrains.kotlin.incremental.storage.PersistentStorageWrapper.close(PersistentStorage.kt:109)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
		... 26 more
	Suppressed: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\lookups: id-to-file.tab, file-to-id.tab
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:93)
		at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.close(BasicMapsOwner.kt:45)
		at org.jetbrains.kotlin.incremental.LookupStorage.close(LookupStorage.kt:155)
		... 25 more
		Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.
			at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
			at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
			at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:24)
			at org.jetbrains.kotlin.incremental.storage.LegacyFileExternalizer.save(IdToFileMap.kt:51)
			at org.jetbrains.kotlin.incremental.storage.LegacyFileExternalizer.save(IdToFileMap.kt:48)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:378)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:360)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:102)
			at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
			at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.applyChanges(InMemoryStorage.kt:108)
			at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:136)
			at org.jetbrains.kotlin.incremental.storage.PersistentStorageWrapper.close(PersistentStorage.kt:109)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
			... 27 more
		Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.
			at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
			at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
			at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:24)
			at org.jetbrains.kotlin.incremental.storage.FileDescriptor.getHashCode(FileToPathConverter.kt:50)
			at org.jetbrains.kotlin.incremental.storage.FileDescriptor.getHashCode(FileToPathConverter.kt:30)
			at org.jetbrains.kotlin.com.intellij.util.containers.hash.HashUtil.hash(HashUtil.java:24)
			at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap.remove(LinkedHashMap.java:149)
			at org.jetbrains.kotlin.com.intellij.util.containers.SLRUMap.remove(SLRUMap.java:116)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.flushAppendCache(PersistentMapImpl.java:924)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:386)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:360)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:102)
			at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
			at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.applyChanges(InMemoryStorage.kt:108)
			at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:136)
			at org.jetbrains.kotlin.incremental.storage.PersistentStorageWrapper.close(PersistentStorage.kt:109)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
			... 27 more
	Suppressed: java.lang.Exception: Could not close incremental caches in D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\build\location\kotlin\compileDebugKotlin\cacheable\caches-jvm\inputs: source-to-output.tab
		... 27 more
		Suppressed: java.lang.IllegalArgumentException: this and base files have different roots: C:\Users\setsi\AppData\Local\Pub\Cache\hosted\pub.dev\location-7.0.0\android\src\main\java\com\lyokone\location\FlutterLocationService.kt and D:\Users\setsi\Documents\Dev\Flutter\Course Academind\12_native_device_features\fav_places\android.
			at kotlin.io.FilesKt__UtilsKt.toRelativeString(Utils.kt:117)
			at kotlin.io.FilesKt__UtilsKt.relativeTo(Utils.kt:128)
			at org.jetbrains.kotlin.incremental.storage.RelocatableFileToPathConverter.toPath(RelocatableFileToPathConverter.kt:24)
			at org.jetbrains.kotlin.incremental.storage.FileDescriptor.getHashCode(FileToPathConverter.kt:50)
			at org.jetbrains.kotlin.incremental.storage.FileDescriptor.getHashCode(FileToPathConverter.kt:30)
			at org.jetbrains.kotlin.com.intellij.util.containers.hash.HashUtil.hash(HashUtil.java:24)
			at org.jetbrains.kotlin.com.intellij.util.containers.hash.LinkedHashMap.remove(LinkedHashMap.java:149)
			at org.jetbrains.kotlin.com.intellij.util.containers.SLRUMap.remove(SLRUMap.java:116)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.flushAppendCache(PersistentMapImpl.java:924)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:386)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:360)
			at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:102)
			at org.jetbrains.kotlin.incremental.storage.LazyStorage.set(LazyStorage.kt:78)
			at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.applyChanges(InMemoryStorage.kt:108)
			at org.jetbrains.kotlin.incremental.storage.AppendableInMemoryStorage.applyChanges(InMemoryStorage.kt:175)
			at org.jetbrains.kotlin.incremental.storage.InMemoryStorage.close(InMemoryStorage.kt:136)
			at org.jetbrains.kotlin.incremental.storage.AppendableSetBasicMap.close(BasicMap.kt:157)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner$close$1.invoke(BasicMapsOwner.kt:45)
			at org.jetbrains.kotlin.incremental.storage.BasicMapsOwner.forEachMapSafe(BasicMapsOwner.kt:85)
			... 26 more

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

√ Built build\app\outputs\flutter-apk\app-debug.apk
D/FlutterLocationService(12029): Creating service.
D/FlutterLocationService(12029): Binding to location service.
D/LocationPlugin(12029): Service connected: ComponentInfo{com.example.fav_places/com.lyokone.location.FlutterLocationService}
Connecting to VM Service at ws://127.0.0.1:55146/qYAZP4hBEqU=/ws
D/ProfileInstaller(12029): Installing profile for com.example.fav_places
```

**Comment by hardiklakhalani** [comment]
@SETSinsperion 
In my code I did not have `location` package added but same warnings were showing for other apps.

I replaced following and ALL the warnings gone, ✅

![Image](https://github.com/user-attachments/assets/3a073b47-1e81-4e1c-8969-3de34bea6909)

### OLD:
```gradle
android {
    compileSdkVersion 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    
    kotlinOptions {
        jvmTarget = '1.8'
    }
    ...
    defaultConfig {
       ...
        minSdkVersion 24
        targetSdkVersion 35
        ...
    }
```

### NEW

```gradle
android {
    compileSdkVersion 34
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = '17'
    }
    ...
    defaultConfig {
       ...
        minSdkVersion 24
        targetSdkVersion 35
        ...
    }
```
### My Specs:
```md
[√] Flutter (Channel stable, 3.27.4, on Microsoft Windows [Version 10.0.19045.5371], locale en-IN)
    • Flutter version 3.27.4 on channel stable at C:\src\3.27.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d8a9f9a52e (11 days ago), 2025-01-31 16:07:18 -0500
    • Engine revision 82bd5b7209
    • Dart version 3.6.2
    • DevTools version 2.40.3

[√] Windows Version (Installed version of Windows is version 10 or higher)           
                                                                                     
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)     
    • Android SDK at C:\Users\Hardik\AppData\Local\Android\sdk                       
    • Platform android-35, build-tools 35.0.0                                        
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java           
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)           
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.38)   
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.35026.282
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

```

**Comment by hardiklakhalani** [comment]
@SETSinsperion 
✅✅✅
I found the solution to `Suppressed: java.lang.Exception: Could not close incremental caches in ...`
though, it was not about `location` package but many more.
It's happening due to file read & write access conflicts by your IDE & Java/Kotlin build compiler.
I had multiple OpenJDK/JBR executables in `Task Manager > Process.` I killed them both, then deleted the content of `user/username/.gradle/caches` and closed other IDE & Git Manager then built again. No warnings or errors were shown.

So it was an access conflict/restriction.

**Comment by Lyokone** [comment]
The Android build was overhauled in 9.0.0 (Kotlin 2.2, Android Gradle Plugin 8.11, Gradle 8.14, a proper namespace and compileSdk 36), which clears this class of Kotlin and Gradle build conflict.

https://pub.dev/packages/location/versions/9.0.0

Closing. If a build error still shows up on 9.0.0, please reopen with the full Gradle output.
