### ISSUE TITLE
Approximate location on API level 34

### ISSUE THREAD

**Issue by fozlerabbi321** [Lyokone/flutterlocation#974]
**Describe the bug**
After selecting the approximate location, a new popup appears.Then If click on 'Keep Approximate Location' again, the app stops.

Checking the location status shows 'PermissionStatus.deniedForever'.
![Screenshot_1](https://github.com/user-attachments/assets/4a8c84c4-298f-48ec-b4d8-c10ab39aba86)
![Screenshot_5](https://github.com/user-attachments/assets/e940fc6c-bfd6-4452-8713-c67178f24222)

**Expected behavior**
Get latitude and longitude 

**Tested on:**
 - Android, API Level 34 [emulator and real device both device]
 - Android, Version 17

**Additional logs**
Log --> Location Status: PermissionStatus.deniedForever

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PERMISSION_DENIED, Location permission denied, null, null)
E/flutter (30021): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter (30021): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (30021): <asynchronous suspension>
E/flutter (30021): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
E/flutter (30021): <asynchronous suspension>
E/flutter (30021): #3      MethodChannelLocation.getLocation (package:location_platform_interface/src/method_channel_location.dart:83:9)
E/flutter (30021): <asynchronous suspension>
E/flutter (30021): #4      HomeScreenState.build.<anonymous closure> (package:mafil_app/presentation/screens/home/home_screen.dart:122:37)
E/flutter (30021): <asynchronous suspension>

**Comment by Lyokone** [comment]
Fixed in 9.0.0. Approximate (coarse) location grants are now honored, including on API 34.

https://pub.dev/packages/location/versions/9.0.0

Closing. Thanks for reporting.
