### ISSUE TITLE
NullPointerException on checkPermissions

### ISSUE THREAD

**Issue by oscarshaitan** [Lyokone/flutterlocation#995]
**Describe the bug**

on executing the `location.hasPermission()` 
I got sometimes the error

```
ava.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
	at com.lyokone.location.FlutterLocation.checkPermissions(FlutterLocation.java:331)
	at com.lyokone.location.MethodCallHandlerImpl.onHasPermission(MethodCallHandlerImpl.java:131)
	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:46)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

``` 
this could happens with or without permissions but usually happens on my first call in the system to check that permissions

Im using `location: ^7.0.0` Flutter 3.24.3

**Tested on:**
 - Android, Samsung Galaxy note 22
 - Pixel 3

**Comment by MrAhmedSayedAli** [comment]
any fix

**Comment by baudine-dreamtec** [comment]
Also getting this issue:

 PlatformException(error, Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
I/flutter (23767): 	at com.lyokone.location.FlutterLocation.checkPermissions(FlutterLocation.java:331)
I/flutter (23767): 	at com.lyokone.location.MethodCallHandlerImpl.onHasPermission(MethodCallHandlerImpl.java:131)
I/flutter (23767): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:46)
I/flutter (23767): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter (23767): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter (23767): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.jav
I/flutter (23767): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter (23767): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:367:18)
I/flutter (23767): <asynchronous suspension>
I/flutter (23767): #2      MethodChannelLocation.hasPermission (package:location_platform_interface/src/method_channel_location.dart:100:20)
I/flutter (23767): <asynchronous suspension>

I'm using location: ^8.0.1 Flutter 3.35.2 

I get this intermittently

**Comment by Lyokone** [comment]
Already fixed. The crashing code path no longer exists: the old `onHasPermission` → `checkPermissions()` → `result.error()`-on-a-null-`Result` chain was removed in the Kotlin rewrite. Current `MethodCallHandlerImpl.onHasPermission` calls `location.permissionStatusCode()` directly (a pure permission check, no `Result` field involved), and `checkPermissions()` itself now uses safe-call syntax (`result?.error(...)`) rather than a direct, crashable call. If this still reproduces on the current release, please reopen with a fresh stack trace.
